### ISSUE TITLE
dynamo crashed when launching on a new file of revit2017

### ISSUE THREAD

**Issue by ellipsebd** [DynamoDS/DynamoRevit#1006]
HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D9.Direct3DEx.CreateDeviceEx(Int32 adapter, DeviceType deviceType, IntPtr hFocusWindow, Int32 behaviorFlags, PresentParameters[] presentationParametersRef, DisplayModeEx[] fullscreenDisplayModeRef, DeviceEx returnedDeviceInterfaceOut)
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource..ctor()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.RenderTechniquesManagerPropertyChanged()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.RenderTechniquesManagerPropertyChanged()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

DynamoInstall1.0.1.20160522T0056
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
## Revit version

2017
(Which version of Revit are you using?)
## Operating system

win10
(e.g. Windows 7, Windows 8.1, etc)
## What did you do?

for a new revit file i tried to launch dynamo but it crashes.
(Fill in here)
## What did you expect to see?

active dynamo interface
(Fill in here)
## What did you see instead?

crashed
![capture](https://cloud.githubusercontent.com/assets/13789181/15487675/2656b33c-2171-11e6-817d-1b391c30b4e2.PNG)

(Fill in here)

**Comment by sharadkjaiswal** [comment]
@ellipsebd are you running Dynamo on a virtual machine? If your machine doesn't have graphics card then you may see this exception. @jnealb can you please take a look, what's going on?

**Comment by jnealb** [comment]
@sharadkjaiswal @ellipsebd On it.

**Comment by jnealb** [comment]
@ellipsebd Can you please run the Dxdiag utility on the machine that is giving you the error and send us the output as a file? Thanks, neal.burnham@autodesk.com

**Comment by ellipsebd** [comment]
Hello @Sharad am not using virtual and attached files are about my
gcard...i also feel that, it would be a problem of gcard. The diagnosis of
Fusion360 and Revit 2017 support this thought. I will use extra gcard to
solve this issue. Do you have any recommendation for it? What about Direct
X? I also like to ask you, if dynamo could have the codes to diagnose gcads
like revit or fusion360 and could tell the recommendations as well as could
tell us the causes for its own crashing s? Hope your reply soon.

On Mon, May 30, 2016 at 6:35 AM, Sharad <notifications@github.com> wrote:

> @ellipsebd <https://github.com/ellipsebd> are you running Dynamo on a
> virtual machine? If your machine doesn't have graphics card then you may
> see this exception. @jnealb <https://github.com/jnealb> can you please
> take a look, what's going on?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DynamoDS/DynamoRevit/issues/1006#issuecomment-222421463>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANJn_dO7qt4su5TdbSjdfzxhlSv1VrC_ks5qGoVNgaJpZM4Ik-dD>
> .
>

FUSION360

[GPU Information]
GPU Device: 
GPU RAM: 128 MB
GPU Driver API: DirectX 11.0
GPU Driver Version: Unknown
GPU Driver Date: Unknown

[Graphics Effects Settings]
Anti Aliasing: Off
Ambient Occlusion: On
Object Shadow: Off
Ground Shadow: On
Ground Reflection: Off
Selection Display Style: Normal
Transparency Effect: Better Performance

[Notes]
1. If you see any graphics display abnormalities, updating to the latest graphics card drivers could help resolve them; please check with your GPU vendors to download and install the latest graphics card drivers.

2. If your graphics card is old and doesn't support DirectX 11 well, you may switch to use DirectX 9 through the Graphics Driver option in Fusion 360 preference dialog.

3. The effects could slow down the graphics rendering; try to limit them for optimum performance.

[Limit all effects to provide optimum performance]
Off

**Comment by ellipsebd** [comment]
Hello@Neal Burnham, i dont know about Dxdiag utility, could you give me the
link to dload?

Attached files are about my gcard....i  feel that, it would be a problem of
gcard. The diagnosis of Fusion360 and Revit 2017 support this thought. I
will use extra gcard to solve this issue. Do you have any recommendation
for it? What about Direct X? I also like to ask you, if dynamo could have
the codes to diagnose gcads like revit or fusion360 and could tell the
recommendations as well as could tell us the causes for its own crashing s?
Hope your reply soon.

On Tue, May 31, 2016 at 8:01 PM, Neal Burnham <notifications@github.com>
wrote:

> @ellipsebd <https://github.com/ellipsebd> Can you please run the Dxdiag
> utility on the machine that is giving you the error and send us the output
> as a file? Thanks, neal.burnham@autodesk.com
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DynamoDS/DynamoRevit/issues/1006#issuecomment-222802691>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANJn_bJHqm0FBXrvtgcAnvwc_WzVU46Mks5qHJOKgaJpZM4Ik-dD>
> .
>

FUSION360

[GPU Information]
GPU Device: 
GPU RAM: 128 MB
GPU Driver API: DirectX 11.0
GPU Driver Version: Unknown
GPU Driver Date: Unknown

[Graphics Effects Settings]
Anti Aliasing: Off
Ambient Occlusion: On
Object Shadow: Off
Ground Shadow: On
Ground Reflection: Off
Selection Display Style: Normal
Transparency Effect: Better Performance

[Notes]
1. If you see any graphics display abnormalities, updating to the latest graphics card drivers could help resolve them; please check with your GPU vendors to download and install the latest graphics card drivers.

2. If your graphics card is old and doesn't support DirectX 11 well, you may switch to use DirectX 9 through the Graphics Driver option in Fusion 360 preference dialog.

3. The effects could slow down the graphics rendering; try to limit them for optimum performance.

[Limit all effects to provide optimum performance]
Off

**Comment by jnealb** [comment]
@ellipsebd Just click on the Windows Start button and run "dxdiag" - the utility is bundled with Windows.

**Comment by ellipsebd** [comment]
@NealBurnham Thanks but my windows start and cortana is not working now...a
common problem of win 10....any other ways?

**Comment by jnealb** [comment]
@ellipsebd Is this still an issue?

**Comment by ellipsebd** [comment]
Hi Neal,
It is not.
Thanks.
