### ISSUE TITLE
Dynamo is great but tired off crashes.

### ISSUE THREAD

**Issue by ellipsebd** [DynamoDS/DynamoRevit#1008]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

8.1 and all most stable n daily builds. For this issue-8.1.
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
## Revit version

2015-2016-2017.
(Which version of Revit are you using?)
## Operating system

win 10
(e.g. Windows 7, Windows 8.1, etc)
## What did you do?

i tried to run "Part-03-Editing-Multiple-Parameters" of module 1 of Advance curriculum on its corresponding rvt file....but every time n every version of revit and dynamo just crashed when pressing the run button.
(Fill in here)
## What did you expect to see?

forms must be updated after run.
(Fill in here)
## What did you see instead?

crashing always.
Please make a only one very stable dynamo. Thanks for this great soft.

Object reference not set to an instance of an object.

   at Dynamo.Models.DynamoModel.Dispose()
   at Dynamo.Models.DynamoModel.ShutDownCore(Boolean shutdownHost)
   at Dynamo.Applications.Models.RevitDynamoModel.ShutDownCore(Boolean shutDownHost)
   at Dynamo.Models.DynamoModel.ShutDown(Boolean shutdownHost)
   at Dynamo.ViewModels.DynamoViewModel.PerformShutdownSequence(ShutdownParams shutdownParams)
   at Dynamo.Controls.DynamoView.PerformShutdownSequenceOnViewModel()
   at Dynamo.Controls.DynamoView.WindowClosing(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![capture](https://cloud.githubusercontent.com/assets/13789181/15527357/8314f92c-225b-11e6-99eb-7f383d24dfb6.PNG)

Here is a sum up report for versions i tried several times...

![capture](https://cloud.githubusercontent.com/assets/13789181/15593047/483f7b7c-2398-11e6-942d-4e83a7f35993.PNG)

(Fill in here)

**Comment by ikeough** [comment]
@ellipsebd When a crash happens at startup, do you receive any errors?

**Comment by kronz** [comment]
Please upgrade to the latest version, stability is much better now.

**Comment by ellipsebd** [comment]
Hi Zach,
Thanks and it is, am using the to-date version and no prob at all!
Regards.
