### ISSUE TITLE
Is something more needed to edit/run Python Script node in Revit 2017?

### ISSUE THREAD

**Issue by Ewhite2533** [DynamoDS/DynamoRevit#1019]
Dynamo version:1.0.0.1180
Revit 2017
Windows 10

I was trying to edit a python script in a dynamo file and this error came up.
This is using the Python Script node.
Normally, we get an edit window that i can edit the python script.

Below is the error message I received:

Could not load file or assembly 'IronPython, Version=2.7.0.40, Culture=neutral, PublicKeyToken=7f709c5b713576e1' or one of its dependencies. The system cannot find the file specified.

   at Dynamo.Python.IronPythonCompletionProvider..ctor()
   at PythonNodeModelsWpf.ScriptEditorWindow..ctor(DynamoViewModel dynamoViewModel)
   at PythonNodeModelsWpf.PythonNodeViewCustomization.EditScriptContent()
   at PythonNodeModelsWpf.PythonNodeViewCustomization.view_MouseDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![image](https://cloud.githubusercontent.com/assets/19697529/15727258/f8e89c5c-281a-11e6-839a-ab44a74a16d3.png)

Letting me know what I need to install, change, or updates would be much appreciated!

>close

**Comment by Ewhite2533** [comment]
FYI:
I ran this same script and dynamo file in Revit 2016 and previous version and everything works fine. 
I can run the script, edit it, and apply it to the revit model without issues.
The issue is running the file in Revit 2017.

**Comment by Ewhite2533** [comment]
Weird thing happened. After reinstalling Python on my computer/restarting/ and reopening Revit 2017, everything seems to be working fine. I must have been caught in a loop somewhere causing the previous crash.

**Comment by Ewhite2533** [comment]
test

**Comment by Ewhite2533** [comment]
Reinstalled python and restarted my computer/revit 2017 and everything works normally. I was stuck in a loop somewhere crashing dynamo.
