### ISSUE TITLE
sluggish response, then crash

### ISSUE THREAD

**Issue by ghost** [DynamoDS/DynamoRevit#1289]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1
## Revit version

2016
## Operating system

Win 7
## What did you do?

double-click to search for a node
## What did you expect to see?

it would find the node
## What did you see instead?

I kept getting slow response times - spinny wheel for every action, seemed very sluggish, and then got a crash with the following report:

`Object reference not set to an instance of an object.

   at Dynamo.Controls.NodeView.topControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by kronz** [comment]
@mjkkirschner @ke-yu any ideas what the call stack here is implicating?

**Comment by jnealb** [comment]
@kronz @mjkkirschner @ke-yu This could be related to MAGN-8387

**Comment by kronz** [comment]
Could be.  That bug is linked up with these, which are mouse move related?  
https://github.com/DynamoDS/Dynamo/issues/5218
https://github.com/DynamoDS/Dynamo/issues/5118
@saintentropy this have any relationship to some of the mouse interaction fixes that went in recently?

**Comment by saintentropy** [comment]
@kronz I will take a look

**Comment by johnpierson** [comment]
Closing this out. This was handed off to an internal tracker that we retired years ago, so the reference in the thread no longer resolves and the trail ends here.

If this still reproduces on a current Dynamo and Revit, please open a fresh issue - it will get tracked properly this time.
