### ISSUE TITLE
unable to open dyn file shortly after saving

### ISSUE THREAD

**Issue by ghost** [DynamoDS/DynamoRevit#1308]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1
## Revit version

2016
## Operating system

win 7
## What did you do?

saved my file (it was not pointing at current document) and closed, then reopened from "recent" menu
## What did you expect to see?

my file
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/2157902/18725955/572da3fa-8010-11e6-8cfe-1ec84171eed2.png)

**Comment by AndrewHeumann** [comment]
![image](https://cloud.githubusercontent.com/assets/2157902/18725981/70486cbc-8010-11e6-92c8-455e57a9a42a.png)
now this is happening on every code block I create. hooray

**Comment by AndrewHeumann** [comment]
oh and fyi here's the call stack trace from the main issue here: System.NullReferenceException: Object reference not set to an instance of an object.
   at Dynamo.Applications.Models.RevitDynamoModel.SetRunEnabledBasedOnContext(View newView, Boolean raiseRevitContextAvailableEvent)
   at Dynamo.Applications.Models.RevitDynamoModel.OnWorkspaceAdded(WorkspaceModel workspace)
   at Dynamo.Models.DynamoModel.OpenFileFromPath(String xmlPath, Boolean forceManualExecutionMode)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.DynamoViewModel.Open(Object parameters)

**Comment by mjkkirschner** [comment]
@AndrewHeumann do you have multiple versions of Dynamo installed?

**Comment by AndrewHeumann** [comment]
yeah I think I still have 0.9.2 and 0.8.2 on here

**Comment by mjkkirschner** [comment]
if possible, could you remove these?

**Comment by sharadkjaiswal** [comment]
@AndrewHeumann can you please share your DYN file for investigation? I believe this callstack is fixed in Dynamo 1.2, please try with that.

**Comment by johnpierson** [comment]
Closing this out. This is an environment or add-in conflict rather than a defect in Dynamo for Revit - the cause is identified in the thread above.

If you run into something like this today, the usual first steps are to check the notifications menu in Dynamo for load errors, and to test with other Revit add-ins disabled. If that does not settle it, please open a fresh issue against a current build.
