### ISSUE TITLE
Opening from or saving to a network location - "Method failed with unexpected error code 50."

### ISSUE THREAD

**Issue by jsdbroughton** [DynamoDS/DynamoRevit#1356]
## Dynamo version

1.2
## Operating system

Windows 7 Pro
## What did you do?

Attempt to open from or save to a mapped network location
## What did you expect to see?

Successful open or save action
## What did you see instead?

```
Method failed with unexpected error code 50.

   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.Security.AccessControl.DirectorySecurity..ctor(String name, AccessControlSections includeSections)
   at DynamoUtilities.PathHelper.HasWritePermissionOnDir(String folderPath)
   at DynamoUtilities.PathHelper.IsReadOnlyPath(String filePath)
   at Dynamo.Controls.PathToFileNameConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Practices.Prism.ViewModel.NotificationObject.RaisePropertyChanged(String propertyName)
   at Dynamo.ViewModels.WorkspaceViewModel.ModelPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Core.NotificationObject.RaisePropertyChanged(String propertyName)
   at Dynamo.Models.DynamoModel.<SaveBackupFiles>b__3b()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by kronz** [comment]
Hi @stardotbmp , does your office have any particular firewall, restricted read/write rights, or other security measures for your network locations?

@riteshchandawar have you seen anything like this before?

Thanks
Z

**Comment by stardotbmp** [comment]
Nothing to write home about. It IS intermittent, though it requires a
dynamo 'reboot' to clear the cascade of the issue applying to subsequent
local saves also.

**Comment by kronz** [comment]
@stardotbmp hmm, intermittent you say? Some files work and some don't?  Do the ones that don't work have a space in the name?

**Comment by stardotbmp** [comment]
No spaces no.

It's the sort of intermittent that is about 90% of the time it errors out.

**Comment by riteshchandawar** [comment]
@kronz @stardotbmp , I will take a loot at it today.

BTW, do you have a full access to the Server which you are trying to Save or Open from?

**Comment by QilongTang** [comment]
Looks like an exception occurs while Dynamo checking if current user has written permission on the target location, would you share more info about the specific setup of the network path, like permission wise. This would help us reproduce the bug.

**Comment by johnpierson** [comment]
Closing this out - this looks like a display or environment issue rather than a defect, and it is many years old.

If it still affects you on a current build, please open a fresh issue.
