### ISSUE TITLE
Dynamo crash

### ISSUE THREAD

**Issue by dago2015** [DynamoDS/DynamoRevit#1415]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1

## Revit version

2016

## Operating system
Windows 7

## What did you do? 
Hit run. I am upgrading a graph from version 1.0.0 to 1.2.1. When I hit run the graph crashes. The graph is supposed to take all the structural elements in a model and write their information into a txt file that is them imported to an analysis software package. I would like to know why this is happening. I have included the graph here.

[11.30.16 - 2.45 RC Export v1.2.zip](https://github.com/DynamoDS/DynamoRevit/files/625682/11.30.16.-.2.45.RC.Export.v1.2.zip)

## What did you expect to see?

txt file

## What did you see instead?

Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.

   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at ProtoCore.ConsoleOutputStream.Write(OutputMessage message)
   at ProtoCore.RuntimeStatus.LogWarning(WarningID ID, String message, String filename, Int32 line, Int32 col)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.DotMethod(StackValue lhs, StackFrame stackFrame, Executive runtime, Context context)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.JILDispatch(List`1 arguments, List`1 replicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore, Context context)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by mjkkirschner** [comment]
@sharadkjaiswal - could this be related to analytics, @jnealb  is this tracked?

**Comment by jnealb** [comment]
@dago2015 Have upgraded to 1.3? Does this issue still occur?

**Comment by ksobon** [comment]
@dago2015 can you answer the question? Is this still an issue in Dynamo 1.3? Thank you.

**Comment by dago2015** [comment]
Yes I did upgrade to 1.3 and the graph still crashes. This is the error report.

Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.

   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at ProtoCore.Lang.Replication.Replicator.EstimateReducedParams(List`1 formalParams, List`1 replicationInstructions, RuntimeCore runtimeCore)
   at ProtoCore.FunctionGroup.GetCastDistances(Context context, List`1 formalParams, List`1 replicationInstructions, ClassTable classTable, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.GetCompliantFEP(Context context, List`1 arguments, FunctionGroup funcGroup, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, Boolean allowArrayPromotion)
   at ProtoCore.CallSite.ComputeFeps(StringBuilder log, Context context, List`1 arguments, FunctionGroup funcGroup, List`1 instructions, List`1 partialReplicationGuides, StackFrame stackFrame, RuntimeCore runtimeCore, List`1& resolvesFeps, List`1& replicationInstructions)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.JILDispatch(List`1 arguments, List`1 replicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore, Context context)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by jnealb** [comment]
@dago2015 What package provides the "Collector.FloorTypes" custom node?

**Comment by dago2015** [comment]
The node comes from spring nodes. I am sure that part is not the problem
because I froze it and ran the code and it still crashed.

**Comment by jnealb** [comment]
Thanks; investigating.

**Comment by jnealb** [comment]
Question: what are your Analytics settings: 
![image](https://cloud.githubusercontent.com/assets/9357222/26594101/6c280932-4534-11e7-8199-c36c3eca679e.png)

**Comment by johnpierson** [comment]
Closing this out as part of a backlog cleanup. The thread went quiet years ago and the versions involved are well behind current.

If this still reproduces on a current Dynamo and Revit, please open a fresh issue with the graph and a sample model attached.
