### ISSUE TITLE
Design Script function errors

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/DynamoRevit#1435]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1.3083

## Revit version

Revit 2017.1

## Operating system

Win 7

## What did you do? 

I defined a DS function to subdivide a curve by chord length

```
def PointByChord(c : var[]..[], chord : double[]..[])
{
	return = [Imperative]
	{
		output = {c.StartPoint};
		val = {};
		n = Math.Ceiling(c.Length / chord) + 1;
		center = c.StartPoint;
		par = 0;
		val[0] = par;
		for (i in 1..n)
		{
			s = Sphere.ByCenterPointRadius(center, chord);
			p = s.Intersect(c)[-1].EndPoint;

			param = c.ParameterAtPoint(p);

			if(param == 1)
			{
				output[Count(output)] = c.EndPoint;
				break;
			}

			if (p.DistanceTo(output[-1]) > 0)
			{
				output[i] = p;
				if (param > par)
				{
					par = param;

				}
				val[i] = par;
				center = c.PointAtParameter(par);
			}
			else
			{
				break;
			}
		}

		return = output;
	}
};

//this function instead creates pairs

def Pairs(list : var[]..[])
{
	output = {};
	return = [Imperative]
	{
		//output = {};
		for (i in 0..Count(list) - 2)
		{
			output[i] = {list[i], list[i + 1]};
		}
		return = output;
	}

};

```
## What did you expect to see?
Pairs(PointByChord(c, 2.2));

A list of point pairs

## What did you see instead?
Dynamo is thoriwin this error and the result of the function returns null for small values

> at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
>    at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
>    at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
>    at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
>    at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
>    at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
>    at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
>    at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
>    at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
>    at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
>    at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
>    at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
>    at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
>    at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by johnpierson** [comment]
Closing this out as part of a backlog cleanup.

This was filed against a version of Dynamo and Revit that is many releases behind current, and it never received a response from us - apologies for that. Without any triage history or a current reproduction there is nothing actionable left here.

If this still happens on a current Dynamo and Revit, please open a fresh issue with the graph and a sample model. A new report against a current build will get far more traction than reviving this one.
