### ISSUE TITLE
Crash on Insertion of Node - Line Styles from Archi-lab_Grimshaw

### ISSUE THREAD

**Issue by Binrock** [DynamoDS/DynamoRevit#1446]
## Dynamo version

(1.2.1.3083)

## Revit version

(Revit 2015 Build:20160512_0715(x64) Update Release 14)

## Operating system

(Windows 7 64Bit sp1)

## What did you do? 

(I was building a graph and on the third node I inserted, the crash occurred. I first inserted the Get Filled Regions collector, next the Collector.ElementSketch.  I wired up Active View Filled Regions output to element(s) input.  Run mode is set to Manual.  When I double clicked the Line Styles node, the crash occurred.)

## What did you expect to see?

(no change)

## What did you see instead?

(bugsplat)

**Comment by Binrock** [comment]
That sequence duplicated resulted in same crash.

Here is the bugsplat:

Method not found: 'Autodesk.Revit.DB.Category Autodesk.Revit.DB.Category.GetCategory(Autodesk.Revit.DB.Document, Autodesk.Revit.DB.BuiltInCategory)'.

   at archilabUI.LineStyleUI.PopulateItemsCore(String currentSelection)
   at CoreNodeModels.DSDropDownBase.PopulateItems()
   at DSRevitNodesUI.RevitDropDownBase..ctor(String value)
   at archilabUI.LineStyleUI..ctor()
   at lambda_method(Closure )
   at Dynamo.Wpf.ViewModels.NodeSearchElementViewModel.OnClicked()
   at Dynamo.UI.Controls.ClassInformationView.ExecuteSearchElement(ListBoxItem listBoxItem)
   at Dynamo.UI.Controls.ClassInformationView.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnPreviewMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ksobon** [comment]
It's Revit 2015. I think it's time to update mate. The latest version of archi-lab package was built and tested against 2017. Either roll back the package to an older version (something from 2 years ago), or please update your Revit version.

**Comment by ksobon** [comment]
@kronz can we close this as well. This has nothing to do with Dynamo Revit and instead is at best a Forum question. Also Revit 2015 is not supported by DynamoRevit anymore so we can close this.

**Comment by kronz** [comment]
@Binrock Yep, sorry, this has to do with a "third party" implementation.  I believe that @ksobon has links from his Archi-lab package to his repository where you can pursue any bugs or requests.

**Comment by Binrock** [comment]
Yeah, I understand. Commercial architects don't always have the luxury of
upgrading to stay on the latest Revit version.  I fixed the problem in c#.
