### ISSUE TITLE
Dynamo crashed when running TASmanianDevil

### ISSUE THREAD

**Issue by mdengusiak** [DynamoDS/DynamoRevit#1621]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
![image](https://cloud.githubusercontent.com/assets/14005893/23817126/af5f04fc-05e8-11e7-9e8d-9f0b089b2d7e.png)

## Revit version

17.0.1081.0

## Operating system

Windows 10

## What did you do? 

I run TASmanianDevil package on Dynamo and control external simulation package. I started and Dynamo crashed

## What did you expect to see?
I expect node to complete

## What did you see instead?
File crashed

Not enough quota is available to process this command

   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ksobon** [comment]
Have a look at this: http://blog.coultard.com/2012/01/fix-windows-error-0x80070718-not-enough.html and this: http://stackoverflow.com/questions/20964360/not-enough-quota-is-available-to-process-this-command-wpf

**Comment by johnpierson** [comment]
Closing this out. The failure here comes from a third-party package rather than from Dynamo for Revit itself, so the package maintainer is much better placed to help.

If you can show the same behaviour using only out-of-the-box nodes, please open a fresh issue and we will take a look.
