### ISSUE TITLE
Opening dynamo file: Acces to the file path is denied

### ISSUE THREAD

**Issue by ThomasBSmits** [DynamoDS/DynamoRevit#1740]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3

## Operating system

Windows 7

## What did you do? 

Trying to open a dynamo file, get message "Acces to the path is denied"

## What did you expect to see?

The Dynamo file i've been working on. Saved it yesterday, but can't acces it anymore. Even previous versions are not accesable anymore. Also tried a different computer/system with other usernames without succes. Other dynamo files, stored in same folder, are working fine,

## What did you see instead?

Error Message: Acces to the file path is denied.

**Comment by ThomasBSmits** [comment]
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.Xml.XmlTextReaderImpl.InitStreamInput(Uri baseUri, String baseUriStr, Stream stream, Byte[] bytes, Int32 byteCount, Encoding encoding)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at Dynamo.Engine.DocumentationServices.GetForAssembly(String assemblyPath, IPathManager pathManager)
   at Dynamo.Engine.XmlDocumentationExtensions.GetMemberDocumentNode(FunctionDescriptor function, XmlReader xml)
   at Dynamo.Engine.XmlDocumentationExtensions.GetMemberElement(FunctionDescriptor function, XmlReader xml, DocumentElementType property, String paramName)
   at Dynamo.Library.TypedParameter.get_Description()
   at Dynamo.Graph.Nodes.ZeroTouch.ZeroTouchNodeController`1.InitializeFunctionParameters(NodeModel model, IEnumerable`1 parameters)
   at Dynamo.Graph.Nodes.ZeroTouch.ZeroTouchNodeController`1.InitializeInputs(NodeModel model)
   at Dynamo.Graph.Nodes.FunctionCallNodeController`1.SyncNodeWithDefinition(NodeModel model)
   at Dynamo.Graph.Nodes.ZeroTouch.ZeroTouchNodeController`1.SyncNodeWithDefinition(NodeModel model)
   at Dynamo.Graph.Nodes.FunctionCallBase`2..ctor(TController controller)
   at Dynamo.Graph.Nodes.ZeroTouch.DSFunctionBase..ctor(ZeroTouchNodeController`1 controller)
   at Dynamo.Graph.Nodes.NodeLoaders.ZeroTouchNodeLoader.CreateNodeFromXml(XmlElement nodeElement, SaveContext context, ElementResolver resolver)
   at Dynamo.Graph.Nodes.NodeLoaders.NodeFactory.LoadNodeModelInstanceByType(Type type, XmlElement elNode, SaveContext context, ElementResolver resolver, NodeModel& node)
   at Dynamo.Graph.Nodes.NodeLoaders.NodeFactory.CreateNodeFromXml(XmlElement elNode, SaveContext context, ElementResolver resolver)
   at Dynamo.Graph.NodeGraph.<>c__DisplayClass1.<LoadNodesFromXml>b__0(XmlElement elNode)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dynamo.Graph.NodeGraph.LoadGraphFromXml(XmlDocument xmlDoc, NodeFactory nodeFactory)
   at Dynamo.Models.DynamoModel.OpenHomeWorkspace(XmlDocument xmlDoc, WorkspaceInfo workspaceInfo, WorkspaceModel& workspace)
   at Dynamo.Models.DynamoModel.OpenFile(WorkspaceInfo workspaceInfo, XmlDocument xmlDoc, WorkspaceModel& workspace)
   at Dynamo.Models.DynamoModel.OpenFileFromPath(String xmlPath, Boolean forceManualExecutionMode)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.ViewModels.DynamoViewModel.Open(Object parameters)

**Comment by QilongTang** [comment]
This type of exception is thrown when the operating system denies access because of an I/O error or a specific type of security error. If you can confirm that the file has proper read/write rights and current system user does have read/write access to it, then it may indicates that the file is corrupted during the save process based on your description. There should be other ways we can try to recover your file, one is that you can open the `DYN` in note pad and copy the nodes into a newly created `DYN` and try opening the new one. Please let me know if this works for you, if you have steps to reproduce this scenario, that would be very helpful as well.

**Comment by johnpierson** [comment]
Closing this out. This is an environment or add-in conflict rather than a defect in Dynamo for Revit - the cause is identified in the thread above.

If you run into something like this today, the usual first steps are to check the notifications menu in Dynamo for load errors, and to test with other Revit add-ins disabled. If that does not settle it, please open a fresh issue against a current build.
