### ISSUE TITLE
Dynamo Crash After Opening File

### ISSUE THREAD

**Issue by jaiemm** [DynamoDS/DynamoRevit#1746]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.3
## Operating system
Windows 7

## What did you do? 

Saved the file yesterday without any problem. Today, I can no longer open it as it keeps on crashing. What did I do wrong? Please help. Thanks in advance.

## What did you expect to see?

(Fill in here)

## What did you see instead?

Object reference not set to an instance of an object.

   at Dynamo.Controls.Watch3DView.CompositionTargetRenderingHandler(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment]
@jaiemm Can you share your file with us? Are you using Dynamo Studio?

**Comment by johnpierson** [comment]
Closing this out. A reproduction case was requested and never arrived, so there is nothing here we can investigate.

If you can still reproduce this on a current Dynamo and Revit, please open a fresh issue with the .dyn and a sample .rvt attached and we will dig in.
