### ISSUE TITLE
Unhandled exception in Dynamo engine: The virtual machine that powers dynamo is experiencing some unexpected errors internally and...

### ISSUE THREAD

**Issue by anorsworthy** [DynamoDS/DynamoRevit#1817]
## Dynamo version

Dynamo Core 1.3.1.1736
Dynamo Revit 1.3.1.1736 (Update pending 1.3.2.0)

## Revit version

Revit 2017.2

## Operating system

Windows 10

## What did you do? 

Tried to run script

## What did you expect to see?

Successful script i.e. no errors

## What did you see instead?

Unhandled exception in Dynamo engine
The virtual machine that powers Dynamo is experiencing some unexpected errors internally and is likely "having great difficulties pulling itself together. it is "recommended that you save your work now and reload the file. Giving the Dynamo VM a new lease of life can potentially make it feel happier and behave better.

If you don't mind, it would be helpful for you to send us your file. That will make it quicker for us to get these issues fixed.
Runtime exception occured. The type of StackValue is not FunctionIndex

   at ProtoCore.DSASM.StackValue.get_FunctionIndex()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute())

![image](https://user-images.githubusercontent.com/24366877/31679331-9ec16aaa-b325-11e7-9e65-337b32b9e30a.png)

**Comment by amirabehery** [comment]
did u know the cause of this error ? how u solve

**Comment by aparajit-pratap** [comment]
@anorsworthy could you send us your graph or outline the steps you took before you saw this exception. It will greatly help in debugging the issue.

**Comment by amirabehery** [comment]
Thanks Alot for your care really & i'll wait for your answer

**Comment by rexwave** [comment]
I have the same circumstances. The graph runs correctly, without node errors, 
[MacKinnon Interface from Excel to Revit via Dynamo Development.zip](https://github.com/DynamoDS/DynamoRevit/files/2949576/MacKinnon.Interface.from.Excel.to.Revit.via.Dynamo.Development.zip)

**Comment by aparajit-pratap** [comment]
@anorsworthy could you repost this issue with more details in https://github.com/DynamoDS/Dynamo. @mjkkirschner @QilongTang how can we port such issues that don't belong here into DynamoCore repo?

**Comment by rexwave** [comment]
I will post it as you request. It’s where I started, but there’s a notice that if the issue involves Revit, to post where I did.
Cheers,
Dave

**Comment by mjkkirschner** [comment]
@aparajit-pratap GitHub now supports issue transfer!
https://help.github.com/en/articles/transferring-an-issue-to-another-repository

**Comment by johnpierson** [comment]
Closing this out. A reproduction case was requested and never arrived, so there is nothing here we can investigate.

If you can still reproduce this on a current Dynamo and Revit, please open a fresh issue with the .dyn and a sample .rvt attached and we will dig in.
