### ISSUE TITLE
Graph works in pieces but not all at once!

### ISSUE THREAD

**Issue by abawiskar** [DynamoDS/DynamoRevit#1831]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.0.875

## Revit version

2017

## Operating system

Windows 10

## What did you do? 

Ran a graph which does the following -
1. Take Revit family instance and tag as selection inputs
2. Pull a list of all materials loaded in the project
3. Create as many copies of the selected elements in step 1 as required (through some checks)
4. Move the newly created elements to various locations on a plan (move by vector based on initial point and final point)

## What did you expect to see?

An array of family instances in multiple locations with all materials assigned to corresponding elements

## What did you see instead?

The graph works in pieces but not all together. There are 9 instances of a custom node that creates and relocates the copies as described above. Each of them works individually as expected (with all others frozen). However, when all nodes are unfrozen, Dynamo throws this error - 

Index was outside the bounds of the array.

   at ProtoCore.DSASM.Executive.GetProcedureNode(Int32 blockId, Int32 classIndex, Int32 functionIndex)
   at ProtoCore.DSASM.Executive.UpdateMethodDependencyGraph(Int32 entry, Int32 procIndex, Int32 classIndex)
   at ProtoCore.DSASM.Executive.SetupExecutive(Int32 exeblock, Int32 entry)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by mjkkirschner** [comment]
I think we'll need to see the graph and a sample revit file to help - unless @aparajit-pratap any ideas regarding custom nodes and this stack trace?

**Comment by abawiskar** [comment]
Thanks mjkkirschner but I think I found the cause of that error. Once I added a condition to only run the custom node when needed (i.e. input was not empty), vs letting it go through an empty list, it started behaving properly! Thanks for offering to take a look though! Will also be sure to add the graph and file next time (this was my first post here).

**Comment by aparajit-pratap** [comment]
@abawiskar even though you may have found a solution, this looks like a crash with the stack trace shown above, which should not happen in the first place. It would be good if you could share a sample graph and revit file to help us reproduce it.

**Comment by johnpierson** [comment]
Closing this out as part of a backlog cleanup. The thread went quiet years ago and the versions involved are well behind current.

If this still reproduces on a current Dynamo and Revit, please open a fresh issue with the graph and a sample model attached.
