### ISSUE TITLE
Cannot GetItemAtIndex

### ISSUE THREAD

**Issue by Appio81** [DynamoDS/DynamoRevit#1833]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2.2480

## Revit version

2017.2

## Operating system

Windows 7

## What did you do? 

try to "GetItemAtIndex" even with designscript or node. Tried after the watch node on the bottom of graph

## What did you expect to see?

as usual...a list or the element

## What did you see instead?

arrrrrrrggghh...virtual machine...

Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

[CFI-001-WIREFRAME_06.zip](https://github.com/DynamoDS/DynamoRevit/files/1427296/CFI-001-WIREFRAME_06.zip)

**Comment by johnpierson** [comment]
Closing this out as part of a backlog cleanup.

This was filed against a version of Dynamo and Revit that is many releases behind current, and it never received a response from us - apologies for that. Without any triage history or a current reproduction there is nothing actionable left here.

If this still happens on a current Dynamo and Revit, please open a fresh issue with the graph and a sample model. A new report against a current build will get far more traction than reviving this one.
