### ISSUE TITLE
Dynamo 1.3.2 Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by nasipes** [DynamoDS/DynamoRevit#1836]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2.2480

## Revit version

Revit 2017.2 (build 17.0.1146.0) and Revit 2018.2 (18.2.0.51)

## Operating system

Windows 10 Pro version 1703 (build 15063.674)

## What did you do? 

Run the attached script. 
[Copy Parameter Value 0.3.txt](https://github.com/DynamoDS/DynamoRevit/files/1428707/Copy.Parameter.Value.0.3.txt)

This script worked fine until opening with Dynamo Studio and modifying the text in one of the parameter strings. 

Here is a different copy of the script that was created prior to opening in Dynamo Studio. 
[Copy Parameter Value 0.3nonStudio.txt](https://github.com/DynamoDS/DynamoRevit/files/1428792/Copy.Parameter.Value.0.3nonStudio.txt)

It appears that opening the script and saving it from Dynamo Studio is the cause of this error. 

## What did you expect to see?

Copy the values of 2 parameters from one family to another. 

## What did you see instead?

Received the following error. 

Index was outside the bounds of the array.

   at ProtoCore.Lang.ArrayUtilsForBuiltIns.Transpose(StackValue sv, Interpreter runtime)
   at ProtoCore.Lang.BuiltInFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by johnpierson** [comment]
Closing this out as part of a backlog cleanup.

This was filed against a version of Dynamo and Revit that is many releases behind current, and it never received a response from us - apologies for that. Without any triage history or a current reproduction there is nothing actionable left here.

If this still happens on a current Dynamo and Revit, please open a fresh issue with the graph and a sample model. A new report against a current build will get far more traction than reviving this one.
