### ISSUE TITLE
Dynamo and Dynamo Player Crushing

### ISSUE THREAD

**Issue by Etzgroup** [DynamoDS/DynamoRevit#1845]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## What did you do? 

Opened Dynamo within revit

## What did you expect to see?

The menu

## What did you see instead?

this:

There was an error deserializing the object of type CSharpAnalytics.Sessions.SessionState. There are multiple root elements. Line 1, position 2.

   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at CSharpAnalytics.Serializers.AppDataContractSerializer.<Restore>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.WinFormAutoMeasurement.<Load>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Analytics.NET.Google.WinNativeAutoMeasurement.<TryLoad>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Analytics.NET.Google.WinNativeAutoMeasurement.<Load>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSharpAnalytics.BaseAutoMeasurement.<Start>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by QilongTang** [comment]
@Etzgroup Can you send us the file? Looks very likely this file is corrupted somehow.

**Comment by Etzgroup** [comment]
which file ? the dyn. file ?

BTW, found [this theard ](https://forum.dynamobim.com/t/dynamo-crahses-on-startup/10226/4), tried and it worked for some reason. I still would like to know if there is a more under the surface of this error. 

this dynamo for revit is a key feature for me...

**Comment by QilongTang** [comment]
Sorry, I meant the session file. It is an XML file underneath and the exception thrown seems to be deserialization related. If you open that `CSharpAnalytics-MeasurementSession` in some editor which can formalize the context, you should be able to validate using https://www.xmlvalidation.com/ and see next steps

**Comment by johnpierson** [comment]
Closing this out - this was resolved in the thread above and never closed.

If it comes back on a current build, please open a fresh issue.
