### ISSUE TITLE
Node and Package Paths_Error when updating settings

### ISSUE THREAD

**Issue by EmCru** [DynamoDS/DynamoRevit#1859]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.2.2480

## Revit Version

17.0.1150.0
20171027_0315(x64)
2017.2.3 

## Operating system

w10

## What did you do? 

Trying to accept and apply changes to my node and package paths.

## What did you expect to see?

Expected update to process

## What did you see instead?

This has been happening a lot recently.  This one causes revit to freeze out and I have to go to the windows task manager to hard close Revit.

![image](https://user-images.githubusercontent.com/24195138/32741166-277a94d6-c85a-11e7-8999-b7b321818a16.png)

[Text in full from dynamo error......
Object reference not set to an instance of an object.

   at Dynamo.ViewModels.SearchViewModel.UpdateEntry(NodeSearchElement entry)
   at System.Action`1.Invoke(T obj)
   at Dynamo.Search.SearchDictionary`1.OnEntryUpdated(V entry)
   at Dynamo.Search.SearchLibrary`2.Update(TEntry entry, Boolean isCategoryChanged)
   at Dynamo.Models.DynamoModel.<>c__DisplayClass26.<>c__DisplayClass28.<InitializeCustomNodeManager>b__22(CustomNodeInfo newInfo)
   at System.Action`1.Invoke(T obj)
   at Dynamo.Core.CustomNodeManager.OnInfoUpdated(CustomNodeInfo obj)
   at Dynamo.Core.CustomNodeManager.SetNodeInfo(CustomNodeInfo newInfo)
   at Dynamo.Core.CustomNodeManager.AddUninitializedCustomNodesInPath(String path, Boolean isTestMode, Boolean isPackageMember)
   at Dynamo.PackageManager.PackageLoader.LoadCustomNodesAndPackages(LoadPackageParams loadPackageParams, CustomNodeManager customNodeManager)
   at Dynamo.ViewModels.PackagePathViewModel.CommitChanges(Object param)
   at Dynamo.Wpf.Views.PackageManager.PackagePathView.OnOkButtonClicked(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)]

**Comment by johnpierson** [comment]
Closing this out as part of a backlog cleanup.

This was filed against a version of Dynamo and Revit that is many releases behind current, and it never received a response from us - apologies for that. Without any triage history or a current reproduction there is nothing actionable left here.

If this still happens on a current Dynamo and Revit, please open a fresh issue with the graph and a sample model. A new report against a current build will get far more traction than reviving this one.
