### ISSUE TITLE
Unhandled exeption when List.ContainsItem is set to @L1

### ISSUE THREAD

**Issue by juliekidder** [DynamoDS/DynamoRevit#1876]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core (& Revit) 1.3.2.2480

## Revit version

2017.2

## Operating system

Windows 10

## What did you do? 

Used list.ContainsItem with list @L1

## What did you expect to see?

A result rather than the error.

## What did you see instead?

Unhandled exception in Dynamo engine (consistently occurs even after restarting Dynamo, doesn't always happen in a new file.

Specified cast is not valid.

   at ProtoCore.DSASM.Heap.ToHeapObject[T](StackValue heapObject)
   at ProtoCore.Lang.Replication.AtLevelHandler.GetElementsAtLevel(StackValue argument, Int32 level, List`1 indices, Boolean recordIndices, RuntimeCore runtimeCore)
   at ProtoCore.Lang.Replication.AtLevelHandler.<>c__DisplayClass6.<GetElementsAtLevel>b__1(StackValue v, Int32 i)
   at System.Linq.Enumerable.<ZipIterator>d__60`3.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProtoCore.Lang.Replication.AtLevelHandler.GetArgumentAtLevel(StackValue argument, AtLevel atLevel, RuntimeCore runtimeCore)
   at ProtoCore.Lang.Replication.AtLevelHandler.GetArgumentsAtLevels(List`1 arguments, List`1 atLevels, RuntimeCore runtimeCore)
   at ProtoCore.Lang.Replication.AtLevelHandler.GetArgumentAtLevelStructure(List`1 arguments, List`1 atLevels, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by kronz** [comment]
@juliekidder can you say a little more about how you are creating this error?  As you say, it does not always reproduce, and I can't repro in a simple situation
![2017-12-10_1844](https://user-images.githubusercontent.com/3456818/33810971-49730ede-ddda-11e7-94aa-39db6d76a6ee.png)

**Comment by juliekidder** [comment]
Here's a zip with the script I was working on (its a bit messy) and a snip of the point where it errors.  I have a flattened list of views, and am trying to find the index where each occurs.  While it's possible I'm feeding it something wrong, I think it should be an error at the node, not an unhandled exception.
[List.contains Error.zip](https://github.com/DynamoDS/DynamoRevit/files/1556202/List.contains.Error.zip)
![list containsitem error](https://user-images.githubusercontent.com/34110095/33949307-784a01a0-dfe6-11e7-85a4-902d168ae0fa.PNG)

**Comment by jnealb** [comment]
@juliekidder This is tracked with QNTM-3024. Thanks!
