### ISSUE TITLE
Crash using levels in List.Transpose node

### ISSUE THREAD

**Issue by StephanvdHeijden** [DynamoDS/DynamoRevit#1878]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Revit 1.3.1.1736

## Revit version

Revit2017

## Operating system

Windows 7,

## What did you do? 

I was extracting propperty information and Area from a revit model. Hereby I wanted to sort the information and add similair Revit-objects with the same discription. I managed to sort the information but am unable to assaign the discription back to the Area's in a list. 

![listtranspose-crashes](https://user-images.githubusercontent.com/34265393/33595904-1cf7c7d0-d99a-11e7-80e3-40ce8e3ec5b5.png)

## What did you expect to see?

A list of list with discriptions with there area's.

## What did you see instead?

Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by jnealb** [comment]
@StephanvdHeijden Can you please attach the dyn graph? Thanks.

**Comment by StephanvdHeijden** [comment]
Hey @jnealb I have got my script working an other way. But here is the script that gave the report. 

[Export .zip](https://github.com/DynamoDS/DynamoRevit/files/1534573/Export.zip)

**Comment by jnealb** [comment]
Thanks @StephanvdHeijden - we can reproduce the crash and are tracking it with QNTM-2957.
