### ISSUE TITLE
Runtime exception occured. The Type of StackValue is not Integer

### ISSUE THREAD

**Issue by Julian-Krab** [DynamoDS/DynamoRevit#1987]
## Dynamo version

1.3.2.2480

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

2018.2

## Operating system

Windows 10

## What did you do? 

Pressed Run

## What did you expect to see?

Replaced strings.

## What did you see instead?

Runtime exception occured. The Type of StackValue is not Integer

   at ProtoCore.DSASM.StackValue.get_IntegerValue()
   at ProtoCore.DSASM.Executive.GetCurrentScope(Int32& classIndex, Int32& functionIndex)
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by Julian-Krab** [comment]
After restarting Dynamo issue disappeared.

**Comment by ksobon** [comment]
@kronz can we close this as not reproducible?
