### ISSUE TITLE
Unhandled Exception - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by moni87d** [DynamoDS/DynamoRevit#1996]
Dynamo 1.3.2.2480
Revit 2016 and 2017
Windows 10

Running quite a big script for model audit and when run in Revit 2016/2017 I get the Unhandled Exception bug report. The script still runs though.
Works fine in Revit 2018.

Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Heap.RecursiveMark(StackValue root)
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()_

Any idea?
Thanks

**Comment by jnealb** [comment]
@moni87d We are releasing D4R 1.3.3 soon, can you please try again with the newer version?

**Comment by ksobon** [comment]
@moni87d we would have to see more from you to be able to re-create the issue here. First and foremost a sample file, Dynamo definition and a small Revit file that we can run it on to re-create the issue. If you are using custom packages in that definition, getting a list of these would help as well. There is a lot of things that can potentially be causing this, and what you posted is not enough for us to debug.

**Comment by moni87d** [comment]
Hi @ksobon and @jnealb - thanks for your help. I have managed to find the area of the script that was causing the problem and shuffled some nodes around to improve the workflow and that seems to have worked. I don't get the error anymore. I was just trying to pull out viewport information to compare viewport families with the viewport types - they were mainly core nodes and some from the Rhythm package. Thanks again.
