### ISSUE TITLE
AvalonEdit.Editing.TextArea.ClearSelection crash

### ISSUE THREAD

**Issue by DavePlumb** [DynamoDS/DynamoRevit#2021]
## Dynamo version

1.3.2 and 2.0

## Revit version

2018.2

## Operating system

 Windows 7 SP1
Fairly large graph, been working on it all morning with no incident
I'm trying to edit a Code Block and get a crash with following error
I've tried closing & restarting several times, and it just doesn't like Code Blocks anymore
Tried to create a new CodeBlock node & got the same crash
I'm running in Manual, (not Automatic). so this appears to be just the Editor, not the compiler

Method not found: 'Void ICSharpCode.AvalonEdit.Editing.TextArea.ClearSelection()'.

   at Dynamo.UI.Controls.CodeCompletionEditor.OnTextAreaLostFocus(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.IsFocused_Changed(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at ICSharpCode.AvalonEdit.Editing.TextArea.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   at System.Windows.DependencyObject.ClearValue(DependencyPropertyKey key)
   at System.Windows.Input.FocusManager.OnFocusedElementChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Input.FocusManager.SetFocusedElement(DependencyObject element, IInputElement value)
   at System.Windows.Input.KeyboardNavigation.UpdateFocusedElement(DependencyObject focusTarget)
   at System.Windows.FrameworkElement.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at Dynamo.Controls.DynamoView.OnRequestReturnFocusToView()
   at Dynamo.ViewModels.DynamoViewModel.OnRequestReturnFocusToView()
   at Dynamo.Controls.NodeView.topControl_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by DavePlumb** [comment]
Same error after a reboot

**Comment by DavePlumb** [comment]
Now this is happening in a brand new Dynamo graph, in a brand new REvit project.
In Revit 2017 and 2018.
I did recently install Dynamo 2.0, but that was last week, and I have done a lot of work before this started happening. Including using Code Blocks.
Even in a clean graph, I get this crash ANY time I try to use a Code Block.

**Comment by DavePlumb** [comment]
**_This is an incompatibility between 1.3.2 and 2.0_**
I uninstalled all versions of Dynamo, then installed just 1.3.2
CodeBlock worked fine
Then I reinstalled 2.0
The error above returned.

**Comment by mjkkirschner** [comment]
@QilongTang we try to preload the avalon edit dll from here to avoid incompatible versions:
https://github.com/DynamoDS/DynamoRevit/blob/8e254612f9be6bdf72cb4a04a6de746ea31c6aa4/src/DynamoRevit/DynamoRevit.cs#L396

@smangarole have you tested side by side with these versions?

@DavePlumb do you see any errors or notifications in the dynamo notifications menu (green circle)

**Comment by DavePlumb** [comment]
I assume you mean the Notifications next to "Help"?
Nothing there
![image](https://user-images.githubusercontent.com/18071127/39215741-a4aea86c-47de-11e8-9b6a-11fa7faab353.png)

**Comment by mjkkirschner** [comment]
so it looks like you are showing 1.3.2 there, does this also happen with 2.0 after the install... - it seems unlikely but it might be worth removing dynamo packages / revit addins. If there was a conflict with an addin I would expect to see a notification about it- so this bizarrely seems to be a conflict with revit's dependencies itself... which is pretty odd.

It has come up before though, before we tried loading the dll from revit ... Revit maybe have changed the location where we try to preload from I guess...

you can try the workaround suggested in other posts you can find on the same issue - remove the dynamo avalonedit dll...
https://forum.dynamobim.com/t/dead-code-block-nodes-in-d4r/8132

It's possible that your 1.3.2 installation has the dll removed somehow but not the 2.0 installer. Was 1.3.2 rolled out through an enterprise system perhaps?

**Comment by DavePlumb** [comment]
I do have another copy of AvalonEdit.dll - from the pyRevit AddIn.
But Dynamo 1.3.2 runs fine with pyRevit.
It only crashes when I install 2.0 (2.0 is NOT installed in this screenshot)
![image](https://user-images.githubusercontent.com/18071127/39260643-b6c6f512-487f-11e8-9d76-51c159ea037a.png)

**Comment by mjkkirschner** [comment]
I don't think pyRevit actually uses that dll anymore.

can you confirm that both 1.3.2 and 2.0 are busted when you install 2.0? Or is only 1.3.2 broken?

**Comment by smangarole** [comment]
@DavePlumb @mjkkirschner I am not able to reproduce this issue. I installed Revit 2016 and 17 on a machine. Removed all Dynamo versions, cleaned up the registry and then installed 1.3.2 and 2.o on top of 1.3.2. Please note that I was using winodows 10. 
I tried editing the code block in a script. Did not get a crash.

**Comment by jnealb** [comment]
@DavePlumb @smangarole Do you have other Revit Addins installed?

**Comment by johnpierson** [comment]
Closing this out. This is an environment or add-in conflict rather than a defect in Dynamo for Revit - the cause is identified in the thread above.

If you run into something like this today, the usual first steps are to check the notifications menu in Dynamo for load errors, and to test with other Revit add-ins disabled. If that does not settle it, please open a fresh issue against a current build.
