### ISSUE TITLE
Dynamo crash with every note

### ISSUE THREAD

**Issue by Thommmyy** [DynamoDS/DynamoRevit#2048]
Did a clean install and it still crashes. Help??

## Dynamo version

1.3.2.2480

## Operating system

Windows 10

## What did you do? 

Everything i do now will give this error. saying the vertual machine is not working.

## What did you expect to see?

Getting elements of a Revit model.

## Error log

Object reference not set to an instance of an object.

   at ProtoCore.Utils.StringUtils.CompareString(StackValue s1, StackValue s2, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.EQ_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang, List`1 breakpoints)
   at ProtoCore.Lang.JILFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by Thommmyy** [comment]
ATM, i found out that it only was not working with Conduit Fittings.  

I'm still curious what the log is saying??

**Comment by jnealb** [comment]
@Thommmyy Can you share your Dynamo graph and Revit model with us? Are you running Revit 2016?

**Comment by Thommmyy** [comment]
@jnealb  Thnx for your comment,

We use Revit 2017.
The working files:
https://we.tl/Iv6OxVsotP

Made a Detached Central file.
ziped my packages en shared my Dynamoscript to transfer elements into the worksets i want them to be in.

**Comment by jnealb** [comment]
@Thommmyy We can reproduce this crash thanks to the data you provided and will report back.

**Comment by Thommmyy** [comment]
@jnealb any progress? 

As temporary solution i made a separate graph for only Conduits / Fittings. Sometimes it works, sometime same issue. checked the component families but could find any strange things yet.

**Comment by Thommmyy** [comment]
@smangarole @kronz 

Here new upload of the working files if needed:
[https://we.tl/cUs5GDMeJl](url)

@jnealb Thanks for the fast repley

**Comment by smangarole** [comment]
@Thommmyy For some reason the files link does not work for me. Takes me to github 404 page. The previous link expired. Can you please check? And share those files again?

**Comment by Thommmyy** [comment]
@smangarole  made a new one
https://we.tl/76EDJiMt6R

**Comment by smangarole** [comment]
Thanks @Thommmyy. Looking at it now.

**Comment by Thommmyy** [comment]
@smangarole  Did you find anything??

**Comment by smangarole** [comment]
@Thommmyy I tried opening the Revit model you provided and it gives me errors when I open it in Revit 2017. I tried opening the DYN file you provided with a different Revit model. Did not get a crash.

**Comment by smangarole** [comment]
@Thommmyy Another update: I get the same error. I am going to escalate this to the D4R team. Tracked internally by: https://jira.autodesk.com/browse/REVIT-133817
@philxia1 Please note

**Comment by Thommmyy** [comment]
@smangarole  Really thanks!!  i don't find where i can make a at "jira.autodesk" to keep follow the issue. 

"Not a member? To request an account, please contact your JIRA administrators.",  is one of you guys this?

**Comment by smangarole** [comment]
@Thommmyy It's accessible internally in Autodesk only. We will update the task here as we make progress.

**Comment by Thommmyy** [comment]
@jnealb @smangarole  is there any news to share or any status of the issue made-up at "Autodesk jira" ??

**Comment by Amoursol** [comment]
Fixed a while ago, closing the loop here.
