### ISSUE TITLE
Dynamo Crashes I close

### ISSUE THREAD

**Issue by jowens012003** [DynamoDS/DynamoRevit#2080]
## Dynamo version

(1.3.3)

## Revit version

(2018.3)

## Operating system

(Windows 10 Pro)

## What did you do? 

(Closed Dynamo)

Here is the bug code
Method not found: 'System.Threading.Tasks.Task CSharpAnalytics.BaseAutoMeasurement.StopRequesterAsync()'.

   at Analytics.NET.Google.WinNativeAutoMeasurement.<Stop>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Analytics.NET.Google.WinNativeAutoMeasurement.Stop()
   at Analytics.NET.Google.GAClient.Stop()
   at Analytics.NET.Google.ApplicationLifeCycleTracker.Track(IAnalyticsEvent event, IAnalyticsClient client)
   at Analytics.NET.Google.GAEventTracker.Track(IAnalyticsEvent event, IEventTrackerFactory factory)
   at Autodesk.Analytics.Core.Service.Track(AnalyticsEvent analyticsEvent)
   at Autodesk.Analytics.Events.ApplicationLifeCycleEvent.Track()
   at Autodesk.Analytics.Events.TimedEvent.End()
   at Autodesk.Analytics.Events.ApplicationLifeCycleEvent.Dispose(Boolean disposing)
   at Autodesk.Analytics.Core.Service.Dispose(Boolean disposing)
   at Autodesk.Analytics.Core.Service.ShutDown()
   at Dynamo.Logging.DynamoAnalyticsSession.Dispose()
   at Dynamo.Logging.DynamoAnalyticsClient.Dispose()
   at Dynamo.Logging.Analytics.ShutDown()
   at Dynamo.Models.DynamoModel.ShutDown(Boolean shutdownHost)
   at Dynamo.ViewModels.DynamoViewModel.PerformShutdownSequence(ShutdownParams shutdownParams)
   at Dynamo.Controls.DynamoView.PerformShutdownSequenceOnViewModel()
   at Dynamo.Controls.DynamoView.WindowClosing(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jnealb** [comment]
@jowens012003 Can you please provide us with some more detail: Dyn graph used, Revit model? @smangarole fyi.

**Comment by jnealb** [comment]
Is it possible for you to uninstall Dynamo using the Control Panel and re-install it? You can use the "Most stable" 1.3.3 from Dynamobuilds.com. If you also have older versions of Dynamo installed please uninstall them too.

**Comment by jowens012003** [comment]
I have tried uninstalling and reinstalling Dynamo and Revit 2018.3 as well.  This issue also occurs in Revit 2019. I also have a cross case issue with Autodesk Partner Support with my Dynamo Player Edit Inputs not working and freeze the player and won't allow Dynamo to open, unless I close Revit completely.  Same goes for Dynamo when it closes, I have to close Revit in order to reopen Dynamo again.

Here is a Screencast showing the issue...
https://autode.sk/2m8PZ50

Very mind boggling.

**Comment by jnealb** [comment]
@jowens012003 We think this may be caused by a Revit Addin - can you please try disabling your Addins temporarily to see if the issue still persists? @smangarole @mjkkirschner fyi.

**Comment by johnpierson** [comment]
Closing this out. This is an environment or add-in conflict rather than a defect in Dynamo for Revit - the cause is identified in the thread above.

If you run into something like this today, the usual first steps are to check the notifications menu in Dynamo for load errors, and to test with other Revit add-ins disabled. If that does not settle it, please open a fresh issue against a current build.
