### ISSUE TITLE
Crash with "Node to Code"

### ISSUE THREAD

**Issue by LPav66** [DynamoDS/DynamoRevit#2104]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

Dynamo version 2.0.1
 Revit version 2019
Operating system Windows 10

(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 

Node to code. Dynamo crashes:

Object reference not set to an instance of an object.

   at ProtoCore.Utils.CoreUtils.CreateNodeFromString(String name)
   at Dynamo.Engine.NodeToCode.ShortestQualifiedNameReplacer.RewriteNodeWithShortName(IdentifierListNode node)
   at Dynamo.Engine.NodeToCode.ShortestQualifiedNameReplacer.VisitIdentifierListNode(IdentifierListNode node)
   at ProtoCore.SyntaxAnalysis.AstReplacer.VisitBinaryExpressionNode(BinaryExpressionNode node)
   at Dynamo.Engine.NodeToCode.NodeToCodeCompiler.ReplaceWithShortestQualifiedName(ClassTable classTable, IEnumerable`1 asts, ElementResolver resolver)
   at Dynamo.Graph.Workspaces.NodesToCodeExtensions.ConvertNodesToCodeInternal(WorkspaceModel workspace, EngineController engineController, INamingProvider namingProvider)
   at Dynamo.Models.DynamoModel.ConvertNodesToCodeImpl(ConvertNodesToCodeCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by johnpierson** [comment]
Closing this out as part of a backlog cleanup.

This was filed against a version of Dynamo and Revit that is many releases behind current, and it never received a response from us - apologies for that. Without any triage history or a current reproduction there is nothing actionable left here.

If this still happens on a current Dynamo and Revit, please open a fresh issue with the graph and a sample model. A new report against a current build will get far more traction than reviving this one.
