### ISSUE TITLE
Dynamo can't launch from Ribbon

### ISSUE THREAD

**Issue by jjmontoya721** [DynamoDS/DynamoRevit#2105]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.1

## Revit version

18.3.1.2

## Operating system

Windows 7 Professional

## What did you do? 

Click the Button

## What did you expect to see?

Dynamo

## What did you see instead?

ProtoCore.Exceptions.CompilerInternalException:
Exception of type ‘ProtoCore.Exceptions.CompilerInternalException’ was thrown.
at ProtoCore.AssociativeEngine.Utils.IsGlobalScopeDirty(Executable exe)
at ProtoScript.Runners.LiveRunner.ApplyUpdate()
at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(String code)
at ProtoScript.Runners.LiveRunner.UpdateCmdLineInterpreter(Sring code)
at Dynamo.Engine.EngineController.OnLibraryLoaded()
at Dynamo.Engine.EngineController.ctor(LibraryServices libraryServices, String geometryFactoryFileName, Boolean verboseLogging)
at Dynamo.Models.DynamoModel.ResetEngineInternal()
at Dynamo.Models.DynamoModel..ctor(IStartConfiguration config)
at Dynamo.Applications.Models.RevitDynamoModel..ctor(IRevitStartConfiguration configuration)
at Dynamo.Applications.DynamoRevit.InitializeCoreModel(DynamoRevitCommandData commandData)
at Dynamo.Applications.DynamoRevit.ExecuteCommand(DynamoRevitCommandData commandData)

**Comment by jjmontoya721** [comment]
@jnealb Dynamo won't open therefore I cannot.

**Comment by jnealb** [comment]
so you get this message when you try to load Dynamo?

**Comment by jjmontoya721** [comment]
Yes, that is correct.

**Comment by jnealb** [comment]
what version of Revit?

**Comment by jjmontoya721** [comment]
18.3.1.2

**Comment by DanimoSite** [comment]
I have the same problem for Dynamo 2.0.3 (across all Revit versions - 2017 to 2019). I click the Dynamo btn, hit 2.0.3 and this is what I get. 

![image](https://user-images.githubusercontent.com/37482336/63967634-c379fb80-ca95-11e9-9556-7ed682483f8b.png)

Revit is up to date with latest updates. I have removed Dynamo (core/Revit) and reinstalled and still getting the same error. Using Windows 10, again all up to date. An ideas on how to fix?

**Comment by tchonky** [comment]
Did you guys find a solution? I'm using Revit 2023 and I'm getting the same error. I cannot open dynamo because of this error.
I have uninstalled and installed Revit again, it works for a few days and then, same error and I cannot use even the Dynamo Player.
I really don't know what may causing this, Have tried [this](https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Dynamo-is-not-launching-from-the-manage-tab-in-Revit.html) Also did not work.

And Dynamo works in the other Revit versions (2024, 2022, 2021)

![Error](https://github.com/DynamoDS/DynamoRevit/assets/79454777/48d93833-f63f-4cb1-a784-91fae9d39f65)

**Comment by avidit** [comment]
tracked internally [DYN-6171](https://jira.autodesk.com/browse/DYN-6171)

**Comment by jasonstratton** [comment]
These stack traces are commonly related to a conflict with an add-in. Please try removing the add-ins and try again.

If it still occurs, please give us a list of the loaded binaries using Process Explorer. This helps diagnose which assembly could not be loaded. Thank you.

**Comment by johnpierson** [comment]
Closing this out. The internal ticket (DYN-6171) was closed as Cannot Reproduce — we were not able to get Dynamo to fail launching from the ribbon with the information available.

Launch failures are usually environment specific: an addin conflict, a partial install, or a .NET issue. If this is still happening for you on a current build, please reopen with the Revit journal file and the Dynamo log and we will dig in.
