### ISSUE TITLE
Nodes not displaying in the workspace and UI is frozen after some seconds

### ISSUE THREAD

**Issue by ghost** [DynamoDS/DynamoRevit#2107]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
1.3.2

## Revit version

(Which version of Revit are you using?)
2017.2

## Operating system

(e.g. Windows 7, Windows 8.1, etc)
Windows 10

## What did you do? 

(Fill in here)
Opened a dyn file in Dynamo Revit

## What did you expect to see?

(Fill in here)
Dyn file opening and things working normally.

## What did you see instead?

(Fill in here)
Nodes weren't displaying. Although I can hit Run only for a few seconds after opening the file and it will run. But after those seconds the UI is frozen and I can't access the library, menus or any other parts of Dynamo. After closing Dynamo I get the following error message:

Method not found: 'System.Threading.Tasks.Task CSharpAnalytics.BaseAutoMeasurement.StopRequesterAsync()'.

   at Analytics.NET.Google.WinNativeAutoMeasurement.<Stop>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Analytics.NET.Google.WinNativeAutoMeasurement.Stop()
   at Analytics.NET.Google.GAClient.Stop()
   at Analytics.NET.Google.ApplicationLifeCycleTracker.Track(IAnalyticsEvent event, IAnalyticsClient client)
   at Analytics.NET.Google.GAEventTracker.Track(IAnalyticsEvent event, IEventTrackerFactory factory)
   at Autodesk.Analytics.Core.Service.Track(AnalyticsEvent analyticsEvent)
   at Autodesk.Analytics.Events.ApplicationLifeCycleEvent.Track()
   at Autodesk.Analytics.Events.TimedEvent.End()
   at Autodesk.Analytics.Events.ApplicationLifeCycleEvent.Dispose()
   at Autodesk.Analytics.Core.Service.ShutDown()
   at Dynamo.Logging.DynamoAnalyticsSession.Dispose()
   at Dynamo.Logging.DynamoAnalyticsClient.Dispose()
   at Dynamo.Logging.Analytics.ShutDown()
   at Dynamo.Models.DynamoModel.ShutDown(Boolean shutdownHost)
   at Dynamo.ViewModels.DynamoViewModel.PerformShutdownSequence(ShutdownParams shutdownParams)
   at Dynamo.Controls.DynamoView.PerformShutdownSequenceOnViewModel()
   at Dynamo.Controls.DynamoView.WindowClosing(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![dynscreenfreeze](https://user-images.githubusercontent.com/36974591/43745497-6527381c-9a22-11e8-9da1-d101b3aec71f.png)

**Comment by johnpierson** [comment]
Closing this out - the report does not contain enough information to act on (the issue template was left largely unfilled), and follow-up requests went unanswered.

If you are still hitting this, please open a fresh issue describing what you did, what you expected, and what happened instead, with the graph attached.
