### ISSUE TITLE
Dynamo Crash after ZeroTouch node complete getting Element Category

### ISSUE THREAD

**Issue by mfleming04** [DynamoDS/DynamoRevit#2123]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.0.1.5055

## Revit version 
2018.3

## Operating system
Windows 7

## What did you do? 
I created a new ZeroTouch simple node to get the elements category.  I placed the new dynamo node into the canvas, selected a revit element from the model and click Run.  It provided me the correct results.  I clicked on a default 3d view and started to draw a new wall and it crashes.  
 
## What did you expect to see?
I should have been able to create a new wall in my empty file and Dynamo should have gathered the next selected element's category.

## What did you see instead?
After successful completing the operation with the ZeroTouch custom node, while trying to select another element or re-run Dynamo crashed with the below info:

Object reference not set to an instance of an object.

   at System.Windows.Controls.Primitives.Popup.OnWindowResize(Object sender, AutoResizedEventArgs e)
   at System.Windows.Interop.HwndSource.Resize(Size newSize)
   at System.Windows.Interop.HwndSource.OnLayoutUpdated(Object obj, EventArgs args)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

My ZeroTouch Code:
using Autodesk.DesignScript.Geometry;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Autodesk.Revit.DB;
using Revit.Elements;  //Taken from RevitNodes dll in Dynamo Folder
using CoreNodeModels;

namespace ZeroTouchNameSpace
{
    public class Revit_Elements
    {
        private Revit_Elements()
        {
        }
        public static Revit.Elements.Category GetCategory(Revit.Elements.Element element)
        {
            Revit.Elements.Category _catFromInput;
            _catFromInput = element.GetCategory;
            return _catFromInput;
        }
    }
}

**Comment by johnpierson** [comment]
Closing this out as part of a backlog cleanup.

This was filed against a version of Dynamo and Revit that is many releases behind current, and it never received a response from us - apologies for that. Without any triage history or a current reproduction there is nothing actionable left here.

If this still happens on a current Dynamo and Revit, please open a fresh issue with the graph and a sample model. A new report against a current build will get far more traction than reviving this one.
