### ISSUE TITLE
Dynamo not reading Revit project file correctly.

### ISSUE THREAD

**Issue by CSFitzgerald** [DynamoDS/DynamoRevit#2222]
This is my first time submitting to GitHub - please be forgiving and kindly advise on submission improvements. I don't know how to attach the relevant **.dyn** file? 

My first instinct would be to post to Dynamo forums, but when it crashes it brings up the "Post to GitHub button", so I presume it should be posted here?

## Dynamo version
Dynamo Core 2.0.1.5055
Dynamo Revit 2.0.1.5065

## Revit version
19.1.0.112
20180806_1515(x64)
2019.1

## Operating system
Windows 10

## What did you do? 
"Clicked Run"

## What did you expect to see?
- "Run Completed."
- Script to run correctly as per usual.

## What did you see instead?
- "Run  started.."
- Script not running correctly, even though correct **.rvt** & **.dyn** are open which were working before. 
- **All Elements of Category** node producing an error and unable to fetch sheets from **Categories** node
![image](https://user-images.githubusercontent.com/43599371/47148362-d72ed000-d2d0-11e8-812b-173691a7201b.png)

**Family Types** node also not working correctly.
![image](https://user-images.githubusercontent.com/43599371/47148442-03e2e780-d2d1-11e8-9e44-ef74bed193c7.png)

When it crashed, it produced the following note:
The managed object is not valid.

   at Autodesk.Revit.DB.Transaction.GetStatus()
   at RevitServices.Transactions.AutomaticTransactionStrategy.ForceCloseTransaction(TransactionHandle handle)
   at Dynamo.Applications.Models.RevitDynamoModel.OnEvaluationCompleted(Object sender, EvaluationCompletedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.OnEvaluationCompleted(EvaluationCompletedEventArgs e)
   at Dynamo.Models.DynamoModel.RunCancelImpl(RunCancelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at Dynamo.Wpf.ViewModels.RunSettingsViewModel.Model_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Dynamo.Core.NotificationObject.RaisePropertyChanged(String propertyName)
   at Dynamo.Models.RunSettings.Reset()
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.Clear()
   at Dynamo.Models.DynamoModel.ClearCurrentWorkspace()
   at Dynamo.ViewModels.DynamoViewModel.ClearHomeWorkspaceInternal()
   at Dynamo.ViewModels.DynamoViewModel.CloseHomeWorkspace(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
I have seen this happen if Dynamo is somehow still attached to a non existent revit doc- I would reboot Dynamo and open a project or family first.

**Comment by CSFitzgerald** [comment]
Hi @mjkkirschner, I figured that restarting solves most issues, so I restarted my PC and tried again prior to posting the above.

**Comment by mjkkirschner** [comment]
So this happens repeatedly, and you have a valid project or family open in revit?

**Comment by CSFitzgerald** [comment]
By 'valid' do you mean 'not corrupt'? 

Yes, it is happening repeatedly in v2.0.1, and it seems to be at random occasions. Sometimes it happens as opening, other times after a different number of nodes inserted, but I am only ever able to add less than 5 nodes before it crashes.

Version 1.3.0 seems to work fine. An added note (not sure if its of value): when trying to open files from my Dynamo backup folder in V1.3.0, it says "file is corrupt" and when trying to open these backups in 2.0.1 it crashes immediately.

**Comment by ZiyunShang** [comment]
Hi @CSFitzgerald , are you still experiencing this issue with the latest Revit & Dynamo version?
If so, I hope you can provide Revit and Dynamo files with this issue.

**Comment by CSFitzgerald** [comment]
Hi @ZiyunShang, this is no longer relevant in the new versions. The latest versions I generally find to be incredibly stable compared to the issues I used to have back then.

Thank you.
