### ISSUE TITLE
Node To Code issue

### ISSUE THREAD

**Issue by HieuQVT** [DynamoDS/DynamoRevit#2254]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo Revit 2.0.1.5065
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
Dynomo Core 2.0.1.5065
Dynamo Revit 2.0.1.5065
## Revit version
Revit 2017
(Which version of Revit are you using?)
Revit 2017
## Operating system
Windows 10, 64 bit
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
Node to code

## What did you expect to see?
Code node

## What did you see instead?
![image](https://user-images.githubusercontent.com/44615901/47734192-222cd980-dc27-11e8-8093-e2fbb616c37a.png)

Detail:
Object reference not set to an instance of an object.

   at ProtoCore.Utils.CoreUtils.CreateNodeFromString(String name)
   at Dynamo.Engine.NodeToCode.ShortestQualifiedNameReplacer.RewriteNodeWithShortName(IdentifierListNode node)
   at Dynamo.Engine.NodeToCode.ShortestQualifiedNameReplacer.VisitIdentifierListNode(IdentifierListNode node)
   at ProtoCore.SyntaxAnalysis.AstReplacer.VisitBinaryExpressionNode(BinaryExpressionNode node)
   at Dynamo.Engine.NodeToCode.NodeToCodeCompiler.ReplaceWithShortestQualifiedName(ClassTable classTable, IEnumerable`1 asts, ElementResolver resolver)
   at Dynamo.Graph.Workspaces.NodesToCodeExtensions.ConvertNodesToCodeInternal(WorkspaceModel workspace, EngineController engineController, INamingProvider namingProvider)
   at Dynamo.Models.DynamoModel.ConvertNodesToCodeImpl(ConvertNodesToCodeCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
(Fill in here)

**Comment by johnpierson** [comment]
Thanks for your report. I am going ahead and closing this here as it is related to [8981](https://github.com/DynamoDS/Dynamo/issues/8981) in the Dynamo Core Repo. This is being worked on this sprint and being tracked.
