### ISSUE TITLE
Unhandled execption -  clockwork node Room.doors

### ISSUE THREAD

**Issue by Christopherbte** [DynamoDS/DynamoRevit#2260]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.1.5055

## Revit version

Revit 2019

## Operating system

W10

## What did you do? 

Run a script with the Room.Doors node

## What did you expect to see?

a completed run

## What did you see instead?

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ProtoCore.FunctionEndPoint.DoesTypeDeepMatch(List`1 formalParameters, RuntimeCore runtimeCore)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at ProtoCore.FunctionGroup.GetExactTypeMatches(Context context, List`1 formalParams, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.GetCompleteMatchFunctionEndPoint(Context context, List`1 arguments, FunctionGroup funcGroup, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ComputeFeps(Context context, List`1 arguments, FunctionGroup funcGroup, List`1 instructions, StackFrame stackFrame, RuntimeCore runtimeCore, List`1& resolvesFeps, List`1& replicationInstructions)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by ksobon** [comment]
CC @andydandy74

**Comment by andydandy74** [comment]
@Christopherbte - Can you file an issue on the Clockwork repo and attach a minimal reproducible case (Dynamo graph and Revit model). Thanks.

**Comment by Christopherbte** [comment]
@andydandy74 
posted! check below
[https://github.com/andydandy74/ClockworkForDynamo/issues/237](url)

**Comment by ZiyunShang** [comment]
Hi @Christopherbte , I saw that you created an issue on the clockwork side, I will turn off the issue here. You can reopen it if needed.
