### ISSUE TITLE
Dynamo Crash while running graph (Unhandled Exception)

### ISSUE THREAD

**Issue by Chrono9084** [DynamoDS/DynamoRevit#2354]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
![image](https://user-images.githubusercontent.com/37596510/53524399-e86cc200-3aa4-11e9-8edb-ed99bcf9e096.png)

## Revit version
![image](https://user-images.githubusercontent.com/37596510/53524438-ff131900-3aa4-11e9-8ce6-211868b87d0f.png)

## Operating system
![image](https://user-images.githubusercontent.com/37596510/53524383-dee35a00-3aa4-11e9-868f-279177ebc3b8.png)

## What did you do? 
Ran a graph.  Got a error window which asked me to post here.

## What did you expect to see?
The graph work as it has in the past.

## What did you see instead?
Unhandled Exception

Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Heap.RecursiveMark(StackValue root)
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Executive.POP_helper(Instruction instruction, Int32& blockId, Int32& dimensions)
   at ProtoCore.DSASM.Executive.POP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by AndyDu1985** [comment]
@Chrono9084  Could upload the .dyn file? And could you do some modification to simplify your graph and find out which node cause the crash? This could help us to find out the root cause.

**Comment by johnpierson** [comment]
Closing this out. A reproduction case was requested and never arrived, so there is nothing here we can investigate.

If you can still reproduce this on a current Dynamo and Revit, please open a fresh issue with the .dyn and a sample .rvt attached and we will dig in.
