### ISSUE TITLE
Dynamo Pop-up warning

### ISSUE THREAD

**Issue by oddman80** [DynamoDS/DynamoRevit#2356]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.3.4

## Revit version
19.2
## Operating system

Windows 10

## What did you do? 

Ran a script

## What did you expect to see?

nothing much

## What did you see instead?

a popup that warned me i should probably save and restartt Dynamo... as welll as this info:

Unable to locate managed object for given dsObject.

   at ProtoFFI.CLRObjectMarshler.CreateCLRObject(StackValue dsObject, Context context, Interpreter dsi, Type type)
   at ProtoFFI.CLRObjectMarshler.UnMarshal(StackValue dsObject, Context context, Interpreter dsi, Type expectedCLRType)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

**Comment by ZiyunShang** [comment]
Hi @oddman80 , could you provide your script to show the case you described? Or could you try to use the latest Revit & Dynamo version instead?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
