### ISSUE TITLE
Python not working

### ISSUE THREAD

**Issue by alfonsomonedero** [DynamoDS/DynamoRevit#2357]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.0.1.5065

## Revit version

2018.3

## Operating system

Windows 10

## What did you do? 

Open Dynamo and place a new python node

## What did you expect to see?

python reading and adding references, it is an empty script, so should work properly

## What did you see instead?

Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. 
Traceback (most recent call last):
  File "<string>", line 3, in <module>
IOError: System.IO.IOException: Could not add reference to assembly ProtoGeometry
   at IronPython.Runtime.ClrModule.AddReference(CodeContext context, String name)
   at IronPython.Runtime.ClrModule.AddReference(CodeContext context, Object[] references)
   at Microsoft.Scripting.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
   at DSIronPython.IronPythonEvaluator.EvaluateIronPythonScript(String code, IList bindingNames, IList bindingValues)

![python error](https://user-images.githubusercontent.com/43339587/53749483-6105c100-3e9f-11e9-99cd-d40a47617c23.png)

**Comment by winterweken** [comment]
If you have pyRevit installed it, try temp removing it form the version your using dynamo. Something to do with IronPython library conflicts.

Re: [485](https://github.com/eirannejad/pyRevit/issues/485)

**Comment by AndyDu1985** [comment]
@alfonsomonedero Is this problem solved?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
