### ISSUE TITLE
Dynamo won't start

### ISSUE THREAD

**Issue by nidhisekhar** [DynamoDS/DynamoRevit#2366]
## Dynamo version

2.0.2

## Revit version

2017

## Operating system

Windows 7

## What did you do? 

Tried opening Dynamo. Then tried uninstalling all Dynamo components and reinstalling.

## What did you expect to see?

The Dynamo Interface

## What did you see instead?

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at DynamoShapeManager.Utilities.PreloadAsmFromPath(String preloaderLocation, String asmLocation)

   at Dynamo.Applications.DynamoRevit.PreloadAsmFromRevit()

   at Dynamo.Applications.DynamoRevit.InitializeCoreModel(DynamoRevitCommandData commandData)

   at Dynamo.Applications.DynamoRevit.ExecuteCommand(DynamoRevitCommandData commandData)

![image](https://user-images.githubusercontent.com/10051875/55177472-ba3cd980-5159-11e9-8514-087abb788379.png)

**Comment by AndyDu1985** [comment]
@nidhisekhar Is this issue resolved?

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
