### ISSUE TITLE
Revit Elements to Solids to Topologic Cells crashes Dynamo

### ISSUE THREAD

**Issue by wassimj** [DynamoDS/DynamoRevit#2384]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
2.1.0
(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version
2020
(Which version of Revit are you using?)

## Operating system
Windows 10
(e.g. Windows 7, Windows 8.1, etc)

## What did you do? 
Tried to convert Dynamo Solids to Topologic Cells.
(Fill in here)

## What did you expect to see?
A list of Topologic Cells
(Fill in here)

## What did you see instead?
Unable to copy the face! : NO_CUR_BB -- no current bulletin board exists

   at Autodesk.LibG.Face.surface_geometry()
   at Autodesk.LibG.FaceHost.SurfaceGeometry()
   at Autodesk.DesignScript.Geometry.Face.SurfaceGeometry()
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Tessellate(Solid solid)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.RevitGeometryObjectFromGraphicItem(IGraphicItem item, List`1& geoms)
   at Dynamo.Applications.ViewModel.RevitWatch3DViewModel.Draw(NodeModel node)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Models.DynamoModel.OnEvaluationCompleted(Object sender, EvaluationCompletedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Dynamo.Graph.Workspaces.HomeWorkspaceModel.OnEvaluationCompleted(EvaluationCompletedEventArgs e)
   at Dynamo.Models.DynamoModel.RunCancelImpl(RunCancelCommand command)
   at Dynamo.Models.DynamoModel.ExecuteCommand(RecordableCommand command)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
(Fill in here)

**Comment by mjkkirschner** [comment]
Hi @wassimj do you implement `IGraphicItem` on the topologic cell class?

This crash is occurring when the revit background preview display is attempting to draw some class - but it's not clear from the stack which object.

**Comment by AndyDu1985** [comment]
Hi @wassimj , could you provide some data to reproduce it?

**Comment by wassimj** [comment]
Hi @mjkkirschner and @AndyDu1985 
ou would need to have Topologic installed (from topologic.app). Then the definition is very simple (only 5 nodes). The problem is sometimes it works and other times it does not.

In Revit 2020, open the Sample Architecture project
In Dynamo, set the Geometry Scaling to "Large"
Create a definition:
The definition is linear and simple (5 nodes strung together from left to right):
Categories (Rooms) ---> All Elements of Category ----> Element.Solids -----> Topology.ByGeometry ----> Topology.Geometry

It is at Topology.Geometry that it seems to be crashing. Topology.Geometry converts Topologies into Dynamo Geometries. We leave the drawing part to Dynamo. So we are not using

**Comment by mjkkirschner** [comment]
in that case I think we'll need to see the source of the node to help (to see the use of Dynamo geometry APIs) (or decompile it if that is acceptable) I do not know if topologic is open source?

**Comment by mjkkirschner** [comment]
@wassimj have you followed this requirement when using the Dynamo geometry library?
https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development#dispose--using-statement

Not implementing this pattern leads to random failures related to memory pressure and the garbage collector. (non deterministic)

We are looking at ways to make this better in the future, but it's a requirement for now.

**Comment by wassimj** [comment]
Thanks for the reply. Yes. We caught a few places where we didn’t follow the pattern. The new version we just announced (0.8.5) has fixed all that. Luckily, we made a conscious design decision early on to interact with Dynamo in only two methods: Topology.ByGeometry and Topology.Geometry. Everything else is independent code.

**Comment by mjkkirschner** [comment]
@wassimj thanks for the update - is this topic still valid or did have you seen this crash again in your latest builds?

**Comment by mjkkirschner** [comment]
@wassimj please reopen if you find this is still an issue.
