### ISSUE TITLE
Unhandled Exception:  Runtime Exception Occured. Dsasm runtime error. Exiting...

### ISSUE THREAD

**Issue by jrob-ACE** [DynamoDS/DynamoRevit#2467]
**Dynamo version:**
Dynamo Core 1.3.2.2480
Dynamo Revit 1.3.2.2480

**Revit version:**  Revit 2018.3

**Operating system:**  Windows 10

I'm not really sure what I did to cause this "unhandled exception", but when I reboot Dynamo, it seems to work again.  The annoying/concerning thing is that I see this error just about every time (intermittently, but frequently) I change something and re-run my code.  I used mostly code blocks for the ability to easily use imperative code.

Because the output I receive (a table with text in a Revit detail view) is what I would expect, I don't really understand why I keep getting this error.  Any help would be greatly appreciated!

**Error Code Text:**
"
Runtime exception occured. Dsasm runtime error. Exiting...

   at ProtoCore.DSASM.Executive.RETCN_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
"

**Comment by ZiyunShang** [comment]
Hi @jrob-ACE , could you try the latest version of Dynamo and DynamoRevit? Or you can support your files (revit file and dyn file), so I can reproduce on my side.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
