### ISSUE TITLE
Dynamo for Revit crashes when exporting huge amount of drafting views as images

### ISSUE THREAD

**Issue by JunKangL** [DynamoDS/DynamoRevit#2571]
## Dynamo version
2.0.3

## Revit version
2018

## Operating system
Windows 10

## What did you do? 
Exporting 700 drafting views as images in a single project

## What did you expect to see?
700 images to be exported

## What did you see instead?
Dynamo crashes with this :
![image](https://user-images.githubusercontent.com/50431530/82971766-0e657700-a006-11ea-9936-4b5529640346.png)
Error Message: 
Not enough quota is available to process this command
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Note: While dynamo for Revit crashes, Revit still runs for a certain amount of time before crashing with a fatal error.

**Comment by ZiyunShang** [comment]
Hi @JunKangL , are you experiencing this issue in latest Dynamo version like 2.5.2? Could you provide a sample for us so that we can reproduce this issue on our side?

**Comment by JunKangL** [comment]
Hi @ZiyunShang, sorry but I couldn't provide you the Revit file as it belongs to the company. I can provide you the dynamo graph though: [JSON_CreateJsonForDocument_v2.0.dyn.txt](https://github.com/DynamoDS/DynamoRevit/files/4687612/JSON_CreateJsonForDocument_v2.0.dyn.txt)

remember to remove the ".txt" fake extension.

And I am experiencing this issue on Dynamo 2.0.3, Revit 2018.

**Comment by ZiyunShang** [comment]
I tried your script and got normal results. I only used 3 rvt files and generated 7 PNG files. I think it may be a very large amount of data that caused the crash. @QilongTang @mjkkirschner Do you have any suggestions for this issue?

**Comment by JunKangL** [comment]
> BTW, in your script, function "RenameFiles(dirpath)":
> newname = fullpath.replace("WSP - Drafting View - ", "")
> I found that not all picture name contains this str - "WSP - Drafting View - " in my tests.

From the remark, you can know that i works at WSP and the view type I am exporting is drafting view 😄 

And yea, I tried it on a single project, with over 700+ drafting views which cause this crash. It will crash when it reaches 150+ images, and the dynamo will just crash with that error while revit continues to export the images until it hits 500+ and finally revit crashes.

**Comment by johnpierson** [comment]
Closing this out. A reproduction case was requested and never arrived, so there is nothing here we can investigate.

If you can still reproduce this on a current Dynamo and Revit, please open a fresh issue with the .dyn and a sample .rvt attached and we will dig in.
