### ISSUE TITLE
Bug Report- Clean Node Layout

### ISSUE THREAD

**Issue by rvida5** [DynamoDS/DynamoRevit#2581]
Object reference not set to an instance of an object.

   at GraphLayout.Edge..ctor(Guid startId, Guid endId, Double startX, Double startY, Double endX, Double endY, Graph ownerGraph)
   at Dynamo.Graph.Workspaces.LayoutExtensions.GenerateCombinedGraph(WorkspaceModel workspace, Boolean isGroupLayout, List`1& layoutSubgraphs, List`1& subgraphClusters)
   at Dynamo.Graph.Workspaces.LayoutExtensions.DoGraphAutoLayout(WorkspaceModel workspace)
   at Dynamo.ViewModels.WorkspaceViewModel.DoGraphAutoLayout(Object o)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ZiyunShang** [comment]
Hi @rvida5 , I think you can ask for Dynamo team help  - https://github.com/DynamoDS/Dynamo/issues .

**Comment by johnpierson** [comment]
Closing this out - this concerns Dynamo core rather than Dynamo for Revit, so this repository is the wrong place for it to be tracked.

If it still reproduces on a current build, please open it against https://github.com/DynamoDS/Dynamo instead.
