### ISSUE TITLE
Returning Autodesk.Revit.DB.Document results in crash if the document is lost

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/DynamoRevit#2582]
## Dynamo version

1.3.x, 2.x.x

## Operating system

Windows 10

## What did you do? 
This is technically a Revit thing, but I think the scope is beyond that..

When you return an `Autodesk.Revit.DB.Document` from a custom zero touch node, you will receive a nasty crash if the document is lost (fairly typical if you use background opened document workflows) and Dynamo is in automatic run mode.

FWIW I "fixed it" with the string fix I mention below. But this basically made it to where my nodes only work with each other. lol

## What would you like to see?

I was curious if there is anyway to prevent the error that results. I have thought about several different ways to do this from view extensions to remove the connection or force to manual run mode. I finally landed on storing the document internally and returning the string name but that isn't great as some nodes require an `Autodesk.Revit.DB.Document` .

## What did you see instead?
```
Object reference not set to an instance of an object.

   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```
## Related Links:
https://forum.dynamobim.com/t/copy-views-to-document-on-file/33448
https://forum.dynamobim.com/t/close-background-revit-files/32837/10

**Comment by mjkkirschner** [comment]
I've transferred this to DynamoRevit because the request at this point seems to be to add a better wrapper for document which better tracks the lifecycle of the document object.

**Comment by mjkkirschner** [comment]
@QilongTang @wangyangshi @honghuiqin FYI - long standing issues here.
1. crashes occurring when document is actually deleted but wrapper still exists
2. authors can't leverage the dynamo document wrapper type and have to all write their own wrappers and convert between them to make packages interoperate. https://www.linkedin.com/feed/update/urn:li:activity:6946172252740624384/

**Comment by erfajo** [comment]
@mjkkirschner, this goes also for Parameters, FamilyDocument, FamilyParameter, and many more classes! Why do you accept classes being shielded?
We did not have any other chance than to create our own wrappers until I saw @johnpierson post... now we can circumvent the limitations... but why do we need to use reflection to solve a problem we never should have had!?
