### ISSUE TITLE
Dynamo crashed while editing Python script

### ISSUE THREAD

**Issue by atultegar** [DynamoDS/DynamoRevit#2586]
I am getting below error while editing python script, and Dynamo crashed.

## Dynamo version

Dynamo Core 2.0.2.6826
Dynamo Revit 2.0.2.6833

## Revit version

2019

## Operating system

Windows 10

## What did you do? 

Editing Python script node

## What did you expect to see?

Python Editor

## What did you see instead?

Error window, saying Dynamo has crashed
![Dynamo Python error](https://user-images.githubusercontent.com/31208705/86773717-31983300-c056-11ea-9a5f-7dfd443f473d.JPG)

Failed to load language 'IronPython 2.7.3': Method not found: '!!1[] Microsoft.Scripting.Utils.ArrayUtils.ConvertAll(!!0[], System.Converter`2<!!0,!!1>)'.

   at Microsoft.Scripting.Runtime.LanguageConfiguration.LoadLanguageContext(ScriptDomainManager domainManager, Boolean& alreadyLoaded)
   at Microsoft.Scripting.Runtime.DlrConfiguration.LoadLanguageContext(ScriptDomainManager manager, LanguageConfiguration config)
   at Microsoft.Scripting.Runtime.DlrConfiguration.TryLoadLanguage(ScriptDomainManager manager, AssemblyQualifiedTypeName providerName, LanguageContext& language)
   at Microsoft.Scripting.Runtime.ScriptDomainManager.GetLanguageByTypeName(String providerAssemblyQualifiedTypeName)
   at Microsoft.Scripting.Hosting.ScriptRuntime.GetEngineByTypeName(String assemblyQualifiedTypeName)
   at Dynamo.Python.IronPythonCompletionProvider..ctor()
   at PythonNodeModelsWpf.ScriptEditorWindow..ctor(DynamoViewModel dynamoViewModel, PythonNode nodeModel, NodeView nodeView, WindowRect& windowRect)
   at PythonNodeModelsWpf.PythonNodeViewCustomization.EditScriptContent()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by atultegar** [comment]
Resolved by reinstalling Dynamo for Revit 2.0.2.
It was due to the automatic uninstall of IronPython 2.7.3 from my system. reinstalling Dynamo 2.0.2 also reinstall IronPython 2.7.3

Thanks

**Comment by QilongTang** [comment]
@atultegar Thanks!
