### ISSUE TITLE
Dynamo has crashed 

### ISSUE THREAD

**Issue by kevalsolanki10** [DynamoDS/DynamoRevit#2592]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo core - 2.1.0.7500
Dynamo Revit - 2.1.0.7733

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

## Revit version - 2019

(Which version of Revit are you using?)

## Operating system

Windows 10

## What did you do? 

Tried to launch the report using the Mandrill. It contain the script of the bar chart.

## What did you expect to see?

Bar chart showing the Room name & Area
## What did you see instead?

Dynamo Crashed
![Crashed](https://user-images.githubusercontent.com/68247813/87343009-d68ca180-c569-11ea-8120-5a8ab845c63f.JPG)

**Comment by kevalsolanki10** [comment]
The process cannot access the file 'C:\Users\Aspire 5\AppData\Roaming\Dynamo\Dynamo Revit\2.1\packages\Archi-lab_Mandrill\bin\eowp.exe' because it is being used by another process.

   at EO.Internal.ji.a(String A_0, Byte[] A_1)
   at Mandrill.ChromeWindow.MandrillWindow..ctor()
   at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
   at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mjkkirschner** [comment]
Hi @kevalsolanki10 please report this to the author of Mandrill:
https://github.com/BadMonkeysTeam/Mandrill/issues

**Comment by kevalsolanki10** [comment]
Thanks
