### ISSUE TITLE
Crash report from Dynamo 2.3.0.5885

### ISSUE THREAD

**Issue by LuisaCPBR** [DynamoDS/DynamoRevit#2612]
# Issue Description
Please fill in the following information to help us reproduce the issue:

I was basically trying to set project information parameters without opening the Revit Files
![immagine](https://user-images.githubusercontent.com/60219049/89410891-d2950f00-d724-11ea-9062-ed36ccda4b87.png)

Like this:
https://forum.dynamobim.com/t/open-files-from-a-directory-and-change-a-parameter-then-re-save-the-file/31326/9

### What did you do?
after I disconected

[Batch Set project parameters on Backgroud.zip](https://github.com/DynamoDS/Dynamo/files/5028261/Batch.Set.project.parameters.on.Backgroud.zip)

 "ʳʰʸᵗʰᵐ|Applications.OpenDocumentFile" Dynamo crashed

### What did you expect to see?
I expected to be able to change the project information parameters without having to open each and every file

### What did you see instead?
(Fill in here)

### What packages or external references (if any) were used?
Orchid
GeniusLoci
Rhythm
BumbleBee

### Stack Trace
```
Unable to locate managed object for given dsObject.

   at ProtoFFI.CLRObjectMarshaler.CreateCLRObject(StackValue dsObject, Context context, Interpreter dsi, Type type)
   at ProtoFFI.CLRObjectMarshaler.UnMarshal(StackValue dsObject, Context context, Interpreter dsi, Type expectedCLRType)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi, List`1 s)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData, FunctionEndPoint finalFep)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.Sweep()
   at ProtoCore.DSASM.Heap.SingleStep(Boolean forceGC)
   at ProtoCore.DSASM.Heap.FullGC(IEnumerable`1 gcroots, Executive exe)
   at ProtoScript.Runners.LiveRunner.ApplyUpdate()
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.3.0.5885`

**Comment by AndyDu1985** [comment]
In this case, seems the Document is become invalid. Could you check if the exception can be catched? @ZiyunShang

**Comment by johnpierson** [comment]
Closing as a duplicate of #2582. As covered in the thread above, the underlying problem is the lack of a lifecycle-aware wrapper for `Autodesk.Revit.DB.Document` — once a background-opened document is closed, the VM still holds a reference to it and crashes on dispose. Tracking that in one place rather than two, so please follow #2582 for any movement on it.
