### ISSUE TITLE
Dynamo Crashed

### ISSUE THREAD

**Issue by mohamedalsheikh11** [DynamoDS/DynamoRevit#2669]
This is the message that appears to me:
Access to the path 'C:\Users\EGYPT_LAPTOP\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN' is denied.

   at Dynamo.Graph.Workspaces.WorkspaceModel.SaveAs(String newPath, RuntimeCore runtimeCore, Boolean isBackup)
   at Dynamo.Models.DynamoModel.<SaveBackupFiles>b__314_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by chuongmep** [comment]
Try Set Properties Full Access for folder C:\Users\EGYPT_LAPTOP\AppData\Roaming\Dynamo\Dynamo Revit\backup, hope can help problem for you.
