### ISSUE TITLE
Generative Design 21.16.10 Crashes

### ISSUE THREAD

**Issue by nickboyts** [DynamoDS/DynamoRevit#2680]
## Dynamo version

2.6
![image](https://user-images.githubusercontent.com/74932642/111328360-2b724180-863c-11eb-99f0-ee635b10bc1a.png)

## Revit version

2021

## Operating system

Windows 10

## What did you do? 

Tried to open Generative Design Tools via Generative Design > Open Generative Design Tools
![image](https://user-images.githubusercontent.com/74932642/111328549-55c3ff00-863c-11eb-9c3c-0952859f2de0.png)

## What did you expect to see?

The panel open

## What did you see instead?

Crash
![image](https://user-images.githubusercontent.com/74932642/111328635-683e3880-863c-11eb-9287-abd75694b4ff.png)
Set property ‘System.Windows.ResourceDictionary.Source’ threw an exception.

at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
at GenerativeDesign.Dynamo.UI.Views.GenerativeDesignMainView…ctor(GenerativeDesignMainViewModel viewModel)
at GenerativeDesign.Dynamo.ViewExtension.GenerativeDesignViewExtension.OpenSidePanel()
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by johnpierson** [comment]
Closing this out. The failure here comes from a third-party package rather than from Dynamo for Revit itself, so the package maintainer is much better placed to help.

If you can show the same behaviour using only out-of-the-box nodes, please open a fresh issue and we will take a look.
