### ISSUE TITLE
Dynamo player destroys graphs

### ISSUE THREAD

**Issue by dimven** [DynamoDS/DynamoRevit#2691]
## Dynamo version

2.6.1
## Revit version

2021

## Operating system

Win 10

## What did you do? 

Ran a nicely laid out and grouped graph through dynamo player

## What did you expect to see?

The same.

## What did you see instead?

This POS:
![image](https://user-images.githubusercontent.com/7148394/115002162-198af500-9ead-11eb-96c6-25606a8b7e76.png)

~100 nodes on top of each other and no more groups 🤦 

And no, the auto node layout (Ctrl + L) is not a solution, because it's oblivious to the logical grouping of the nodes.

## Bonus points:

Now the code blocks are broken too
![image](https://user-images.githubusercontent.com/7148394/115002494-7d152280-9ead-11eb-8dc1-4e155f80c751.png)

**Comment by mjkkirschner** [comment]
Hey @dimven - can you describe your workflow a bit more - maybe some background will help get to the bottom of it.

* AFAIK Player runs graphs without a view, in this mode, none of the view properties are deserialized (like x,y coordinates)
* If saved in this state, the graph will look like your image above. (first image)
* I don't believe player saves graphs though - so my entire line of thinking about what is happening might be incorrect.

Especially given the failure to load the codeblock view - this appears to be some kind of datarace or view layer conflict - Do you have lots of addins and packages installed? (I'll assume yes?)

I think getting the list of loaded modules when this occurs, and maybe a gif of your workflow will help us understand whats going on.

https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls can be used if you don't have visual studio on this machine.

**Comment by dimven** [comment]
The only plugin I have on the Revit side is RevitLookup. However I do have a bunch of packages and a few view extensions in Dynamo:
![image](https://user-images.githubusercontent.com/7148394/115105526-2f112500-9f68-11eb-8f0a-6c8551cc37c2.png)

I dug through the logs from yesterday and this part stood out:
```
2021-04-16 09:08:33Z : Active view is now FSSD-_3D MODEL
2021-04-16 09:08:36Z : Failed to apply NodeViewCustomization for CodeBlockNodeModel
2021-04-16 09:08:36Z : System.NullReferenceException:
2021-04-16 09:08:36Z : Object reference not set to an instance of an object.
2021-04-16 09:08:36Z :    at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateClassHighlightRule(EngineController engineController)
   at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateHighlightingRules(TextEditor editor, EngineController controller)
   at Dynamo.UI.Controls.CodeBlockEditor..ctor(NodeView nodeView)
   at Dynamo.Wpf.CodeBlockNodeViewCustomization.CustomizeView(CodeBlockNodeModel model, NodeView nodeView)
   at lambda_method(Closure , NodeModel , NodeView )
   at Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
2021-04-16 09:08:36Z : Failed to apply NodeViewCustomization for CodeBlockNodeModel
2021-04-16 09:08:36Z : System.NullReferenceException:
2021-04-16 09:08:36Z : Object reference not set to an instance of an object.
2021-04-16 09:08:36Z :    at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateClassHighlightRule(EngineController engineController)
   at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateHighlightingRules(TextEditor editor, EngineController controller)
   at Dynamo.UI.Controls.CodeBlockEditor..ctor(NodeView nodeView)
   at Dynamo.Wpf.CodeBlockNodeViewCustomization.CustomizeView(CodeBlockNodeModel model, NodeView nodeView)
   at lambda_method(Closure , NodeModel , NodeView )
   at Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
2021-04-16 09:08:36Z : Failed to apply NodeViewCustomization for CodeBlockNodeModel
2021-04-16 09:08:36Z : System.NullReferenceException:
2021-04-16 09:08:36Z : Object reference not set to an instance of an object.
2021-04-16 09:08:36Z :    at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateClassHighlightRule(EngineController engineController)
   at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateHighlightingRules(TextEditor editor, EngineController controller)
   at Dynamo.UI.Controls.CodeBlockEditor..ctor(NodeView nodeView)
   at Dynamo.Wpf.CodeBlockNodeViewCustomization.CustomizeView(CodeBlockNodeModel model, NodeView nodeView)
   at lambda_method(Closure , NodeModel , NodeView )
   at Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
2021-04-16 09:08:36Z : Failed to apply NodeViewCustomization for CodeBlockNodeModel
2021-04-16 09:08:36Z : System.NullReferenceException:
2021-04-16 09:08:36Z : Object reference not set to an instance of an object.
2021-04-16 09:08:36Z :    at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateClassHighlightRule(EngineController engineController)
   at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateHighlightingRules(TextEditor editor, EngineController controller)
   at Dynamo.UI.Controls.CodeBlockEditor..ctor(NodeView nodeView)
   at Dynamo.Wpf.CodeBlockNodeViewCustomization.CustomizeView(CodeBlockNodeModel model, NodeView nodeView)
   at lambda_method(Closure , NodeModel , NodeView )
   at Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
2021-04-16 09:08:36Z : Failed to apply NodeViewCustomization for CodeBlockNodeModel
2021-04-16 09:08:36Z : System.NullReferenceException:
2021-04-16 09:08:36Z : Object reference not set to an instance of an object.
2021-04-16 09:08:36Z :    at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateClassHighlightRule(EngineController engineController)
   at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateHighlightingRules(TextEditor editor, EngineController controller)
   at Dynamo.UI.Controls.CodeBlockEditor..ctor(NodeView nodeView)
   at Dynamo.Wpf.CodeBlockNodeViewCustomization.CustomizeView(CodeBlockNodeModel model, NodeView nodeView)
   at lambda_method(Closure , NodeModel , NodeView )
   at Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
2021-04-16 09:08:36Z : Failed to apply NodeViewCustomization for CodeBlockNodeModel
2021-04-16 09:08:36Z : System.NullReferenceException:
2021-04-16 09:08:36Z : Object reference not set to an instance of an object.
2021-04-16 09:08:36Z :    at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateClassHighlightRule(EngineController engineController)
   at Dynamo.Wpf.Views.CodeHighlightingRuleFactory.CreateHighlightingRules(TextEditor editor, EngineController controller)
   at Dynamo.UI.Controls.CodeBlockEditor..ctor(NodeView nodeView)
   at Dynamo.Wpf.CodeBlockNodeViewCustomization.CustomizeView(CodeBlockNodeModel model, NodeView nodeView)
   at lambda_method(Closure , NodeModel , NodeView )
   at Dynamo.Wpf.NodeViewCustomizationLibrary.TryApplyCustomization(NodeModel model, NodeView view, InternalNodeViewCustomization customization)
2021-04-16 09:08:48Z : DynamoPackageManager (id: FCABC211-D56B-4109-AF18-F434DFE48139) extension is removed
2021-04-16 09:08:48Z : Goodbye
```

I suspect the issue was from the Monocle view extension. I updated it and can't replicate the issue any more. It comes with a version of the Xceed Toolkit and so do Dynamo and Revit. My best guess is that was creating a version conflict and the update resolved it.

Isn't there a better way to avoid these issues? Do you know of any event similar to  `AppDomain.AssemblyLoad` or `AppDomain.AssemblyResolve` that triggers before the load and can check if an assembly with that name is already loaded and use it instead?

**Comment by louistrue** [comment]
Happened to me too a few days ago. Used Dynamo Player, then opened graph directly from Player. All nodes in one place, no groups. Also have monocle installed. Closing Revit and reopening the graph in a new revit session resolved the issue for me. Everything went back to normal.

**Comment by johnpierson** [comment]
> I suspect the issue was from the Monocle view extension. I updated it and can't replicate the issue any more. I think I was on the 2020.10.1 version prior to the update. It comes with a version of the Xceed Toolkit and so do Dynamo and Revit. My best guess is this was creating a version conflict and the update resolved it.

The previous version might have still had the Custom Node coloring feature I had before. I removed that recently as I did not like how it iterated through the node views. Do you think the view extension could have been doing this? I have seen similar errors before with graphs "stacking" nodes, (before monocle existed in some cases).

**Comment by BeeBeePrime** [comment]
Here's an improved version of your text:
Subject: Reproducible Issue: Dynamo Graph Destruction in Revit
Hello Dynamo Team,
I'm not sure if anyone is still investigating this issue, but I've managed to reproduce it on my end. This information may help you identify the root cause.

Steps to Reproduce:

1. Open an instance of Dynamo in Revit.
2. 
![tv0BgMdD93](https://github.com/user-attachments/assets/e09390b3-ad72-4cc5-901e-4388d9525cf5)
Use a .NET plugin in Revit. One of the buttons runs a Dynamo script in the background. Here's the relevant method from my C# command class:
```
public class MyPlugin : IExternalCommand
{
    public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
    {
        // Get the path to the Dynamo script
        string assemblyLocation = System.Reflection.Assembly.GetExecutingAssembly().Location;
        string projectDirectory = Path.GetDirectoryName(assemblyLocation);
        string scriptPath = Path.Combine(projectDirectory, "DynamoLibrary", "ExportFieldMarkers.dyn");
        return ExecuteDynamo(commandData.Application, scriptPath);
    }

    public Result ExecuteDynamo(UIApplication uiapp, string path)
    {
        try
        {
            if (!System.IO.File.Exists(path))
            {
                return Result.Failed;
            }
            IDictionary<string, string> journalData = new Dictionary<string, string>
            {
                { JournalKeys.ShowUiKey, false.ToString() },
                { JournalKeys.AutomationModeKey, true.ToString() },
                { JournalKeys.DynPathKey, "" },
                { JournalKeys.DynPathExecuteKey, true.ToString() },
                { JournalKeys.ForceManualRunKey, false.ToString() },
                { JournalKeys.ModelShutDownKey, true.ToString() },
                { JournalKeys.ModelNodesInfo, false.ToString() }
            };
            DynamoRevitCommandData dynamoRevitCommandData = new DynamoRevitCommandData
            {
                Application = uiapp,
                JournalData = journalData
            };
            DynamoRevit dynamoRevit = new DynamoRevit();
            dynamoRevit.ExecuteCommand(dynamoRevitCommandData);
            DynamoRevit.RevitDynamoModel.OpenFileFromPath(path, true);
            DynamoRevit.RevitDynamoModel.ForceRun();
            return Result.Succeeded;
        }
        catch (Exception)
        {
            return Result.Failed;
        }
    }
}
```

3. Run the button.

Result: The Dynamo graph is destroyed. This occurs in both Revit 2021 and Revit 2023.
I hope this information helps in your investigation. Please let me know if you need any additional details or clarification.
Best regards,
