### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by scubaman120** [DynamoDS/DynamoRevit#2698]
## Dynamo version

Core 2.0.3.8810
Revit 2.0.3.8811

## Revit version

19.2.20.24
20190808_0900(x64)
2019.2.2

## Operating system

Windows 10

## What did you do? 

Run graph

## What did you expect to see?

Graph execution 

## What did you see instead?

Dynamo's Virtual machine crashed.
![image](https://user-images.githubusercontent.com/33437179/116458687-c5233600-a819-11eb-8e7a-a5652f991739.png)

```
    Object reference not set to an instance of an object.

       at ProtoCore.Utils.StringUtils.ConcatString(StackValue op1, StackValue op2, RuntimeCore runtimeCore)
       at ProtoCore.Utils.CoreUtils.AddStackValueString(StackValue sv1, StackValue sv2, RuntimeCore runtimeCore)
       at ProtoCore.DSASM.Executive.ADD_Handler(Instruction instruction)
       at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
       at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
       at ProtoCore.DSASM.Interpreter.Run(Int32 codeblock, Int32 entry, Language lang, List`1 breakpoints)
       at ProtoCore.Lang.JILFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
       at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
       at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
       at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
       at ProtoCore.CallSite.ExecWithRISlowPath(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
       at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore)
       at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, DominantListStructure domintListStructure, StackFrame stackFrame, RuntimeCore runtimeCore)
       at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
       at ProtoCore.DSASM.Executive.CALLR_Handler(Instruction instruction)
       at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
       at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, List`1 breakpoints, Language language)
       at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
       at ProtoScript.Runners.ProtoScriptRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
       at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
       at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
       at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
       at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
       at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
       at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
       at Dynamo.Scheduler.AsyncTask.Execute()
```

also posted to the dynamo forum https://forum.dynamobim.com/t/real-or-theoretical-compacity-limits-of-dynamo/63414[](https://forum.dynamobim.com/t/real-or-theoretical-compacity-limits-of-dynamo/63414)

**Comment by johnpierson** [comment]
Closing this out as part of a backlog cleanup.

This was filed against a version of Dynamo and Revit that is many releases behind current, and it never received a response from us - apologies for that. Without any triage history or a current reproduction there is nothing actionable left here.

If this still happens on a current Dynamo and Revit, please open a fresh issue with the graph and a sample model. A new report against a current build will get far more traction than reviving this one.
