### ISSUE TITLE
Crash report from Dynamo 2.10.1.3976

### ISSUE THREAD

**Issue by Amoursol** [DynamoDS/DynamoRevit#2734]
# Issue Description
Please fill in the following information to help us reproduce the issue:

### What did you do?
Opened up the Revit Basic Sample File (RAC_basic_sample_project.rvt) in Revit 2022, using Dynamo 2.10.1. I'm using Parallels to spin up Windows on my Mac.

Used the right-click search menu to place a **Categories** node, but didn't select any dropdown item. Then used the right-click search menu to place an **All Elements of Category" node, at which point DynamoRevit crashed. 

The crash doesn't happen if you choose an item from the dropdown selector, and also doesn't happen if you choose an item from the dropdown selection node, delete all nodes and try to reproduce in the same workspace. It will happen if you start a fresh workspace and take the original actions. 

![image](https://user-images.githubusercontent.com/12857357/127363921-4016a7cc-227e-4fb9-8faf-cee1c230b459.png)

### What did you expect to see?
Non crashing behavior. 

### What did you see instead?
Actions as in the following movie file.

https://user-images.githubusercontent.com/12857357/127364366-6408a946-287a-4266-81f4-33435771b3d9.mov

### What packages or external references (if any) were used?
None in the graph.

### Stack Trace
```
Exception of type 'ProtoCore.Exceptions.CompilerInternalException' was thrown.
   at ProtoCore.Utils.Validity.Assert(Boolean cond)
   at ProtoScript.Runners.ChangeSetApplier.ApplyChangeSetForceExecute(ChangeSetData changeSet)
   at ProtoScript.Runners.LiveRunner.SynchronizeInternal(GraphSyncData syncData)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Scheduler.UpdateGraphAsyncTask.HandleTaskExecutionCore()
   at Dynamo.Scheduler.AsyncTask.Execute()
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.10.1.3976`

**Comment by Amoursol** [comment]
@ZiyunShang - Found a bug, as above 😊 Not sure if it's a Parallels only thing, but would be awesome to get tested to see if it's real before the next Dynamo release.

**Comment by ZiyunShang** [comment]
Hi @Amoursol , I tried to reproduce this issue on my PC. Instead of using remote controls, I operated directly from Windows 10. This crash did not appear. I guess it may be relate to the "Parallels".
Since I don't have an environment like a Mac on my side, I'll ask QA for help to see if it can be reproduced.

**Comment by ZiyunShang** [comment]
Hi @Amoursol , I asked a UX colleague to help me use Dynamo remotely on a Mac and the problem can't be reproduced. I think it's probably Parallels.
Is this a big user value problem for us to fix? And I guess this may be a Dynamo VM problem?

**Comment by Amoursol** [comment]
Hi Ziyun - If you can't reproduce them no problem! Just trying to safeguard the customer 😊 The vast majority of users are on Windows!



On Jul 29, 2021 21:58, ZiyunShang ***@***.***> wrote:

Hi @Amoursol<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAmoursol&data=04%7C01%7Csol.amour%40autodesk.com%7Cf2981167f78e431f46ad08d952fd85d0%7C67bff79e7f914433a8e5c9252d2ddc1d%7C0%7C0%7C637632071093702139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p8DvoVyFKr%2BmwI8P%2F3HNsevPrqNN8vWIPKZVZXse21o%3D&reserved=0> , I asked a UX colleague to help me use Dynamo remotely on a Mac and the problem can't be reproduced. I think it's probably Parallels.
Is this a big user value problem for us to fix? And I guess this may be a Dynamo VM problem?

**Comment by johnpierson** [comment]
Closing this out as not reproducible. Two people tried to reproduce this at the time — one on Windows directly, one on a Mac — and neither saw the crash, which points at Parallels rather than at Dynamo. Dynamo 2.10.1 is also many releases behind at this point.

If this turns up again on a current build, especially outside Parallels, please open a fresh issue and we will take another look.
