### ISSUE TITLE
Crash report from Dynamo 2.12.1.8246

### ISSUE THREAD

**Issue by Human1person** [DynamoDS/DynamoRevit#3380]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.1.8246`

## Operating system
OS: `Microsoft Windows NT 10.0.19045.0`

## What did you do?
I attempted to minimize dynamo. The most recent command was to clean up the nodes.

## What did you expect to see?
I expected Dynamo window to minimize

## What did you see instead?
It crashed, but provided some consolation and all this here data for smarter people to use to maybe address some of the instability that's apparently inherent in Dynamo.

### Loaded Packages
- archi-lab.net 2024.217.1024
- bimorphNodes 4.2.4
- Clockwork for Dynamo 2.x 2.6.0
- DynaMEP 2.0.1
- DynamoMEP 1.0.3
- MEPover 2022.10.30
- GenerativeDesign 1.10.10.0
- GenerativeDesign.Extension 1.10.10.0
- GenerativeDesign.Revit 1.10.10.0
- SteamNodes 1.2.4

## Stack Trace
```
Object reference not set to an instance of an object.

   at Dynamo.WorkspaceDependency.WorkspaceDependencyView.DependencyRegen(WorkspaceModel ws)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
CLR: `4.0.30319.42000`

**Comment by johnpierson** [comment]
Closing this out. Thanks for sending the report through, and for the good humor about it.

Unfortunately there is no stack trace in the report and "crashed while minimizing after a node cleanup" is not something we have been able to tie to anything specific. Dynamo 2.12.1 is also a long way behind current, and the graph layout and window handling code has changed a good deal since.

If this is still happening on a current build, please reopen with the stack trace from the crash dialog (Details -> Copy) and we will dig in.
